### ISSUE TITLE
editor menu arrow disconnect on windows-10-on-bootcamp

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1754] opened 2017-02-17 21:01 UTC
possibly a really specific OS bug: I see a misalignment between the EDITOR menu and the associated triangle pointer on Windows 10 running with bootcamp on a macbook pro

![capture](https://cloud.githubusercontent.com/assets/177243/23083104/266757cc-f511-11e6-88be-a826fb5903b2.PNG)

**Comment by humphd** [comment] 2017-02-17 21:06
Interesting.  I don't get it on Chrome/macOS.  Which browser are you using?

**Comment by Pomax** [comment] 2017-02-17 21:13
both Chrome and Firefox in a bootcamped Windows 10, display set to "2880x1800 (recommended)" with 150% rather than 200% UI scaling

**Comment by flukeout** [comment] 2017-02-17 22:34
One easy fix for this would be to adjust the CSS for the arrow element...

``#editor-pane-nav-options-menu:after``

It currently has a ``top: -15px`` but changing it to ``top: -14px`` would make it so the bottom of the arrow overlaps with the top of the menu box. This would probably solve this and maybe other  zoomign / scaling cases?

**Comment by Pomax** [comment] 2017-02-17 22:59
This looks like it's specifically an issue for 150% scaling on a retina display...

**Comment by flukeout** [comment] 2017-02-17 23:04
Looks like it crops up sometimes when just zooming the browser...

<img width="376" alt="image" src="https://cloud.githubusercontent.com/assets/25212/23086524/3573d81a-f522-11e6-926b-3e8a291340ca.png">

The fix in my previous comment addresses this one too, so let's go with that.

**Comment by rkgupta21** [comment] 2017-02-23 00:23
I would like to work on this bug.

**Comment by humphd** [comment] 2017-02-23 14:48
@rkgupta21 OK, it's yours.

**Comment by rkgupta21** [comment] 2017-03-06 21:51
I could not reproduce this bug on the Google chrome and Mozilla firefox browser on my bootcamp. It only showed up for microsoft Edge.

**Closed** 2017-03-09 20:55 UTC
Labels: Assigned to Contributor, bug, good first bug, UI
