### ISSUE TITLE
Favorites stored in local storage rather than the database

### ISSUE THREAD

**Issue by hkirat** [mozilla/thimble.mozilla.org#1861] opened 2017-03-10 17:44 UTC
Right now if you select a project as your favorite, it is stored in local storage.
Check [this](https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/project-list.js#L60)
This will give different results if the same user opens the projects page in different browsers.
Ideally, there should be a flag in each project indicating whether or not it is in the user's favorites.

**Comment by flukeout** [comment] 2017-03-10 22:09
Yeah, that was an intentional choice to keep the scope of the feature smaller. Ideally, this would be stored at the database level.

**Comment by Pomax** [comment] 2017-03-11 00:29
closing this as a "works as intended". If we want to expand the functionality to a database-synced feature we should file a new, dedicated issue for that.

**Closed by Pomax** 2017-03-11 00:29 UTC
Labels: Feature Request
