### ISSUE TITLE
text cursor instead of pointer for "sign in" and "create new account"

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1493] opened 2016-06-04 17:18 UTC
But only once you're in Thimble proper, on the landing page it's a pointer.

![screenshot 327](https://cloud.githubusercontent.com/assets/177243/15801023/a40c22ba-2a3d-11e6-9c0d-02777cf2bb28.png)

**Comment by gideonthomas** [comment] 2016-06-06 14:37
wow that's new! seems like a regression!

**Comment by rushabhy** [comment] 2016-06-25 16:19
Can I give it a try?

**Comment by gideonthomas** [comment] 2016-06-25 23:23
@rushabhy sure thing! You should start by forking and cloning this repository as well as the dependencies as per the instructions here: https://github.com/mozilla/thimble.mozilla.org#setup

Until then, I'll search for where the code change happens. If you have any issues while setting up, let us know and we'll help you out through the process :)

**Comment by rushabhy** [comment] 2016-06-26 04:07
Thank you for such a warm welcome! Done with the installation. 
I was looking around and found that the cursor problem is because the anchor tag doesn't have `href` attribute. There are two solutions which I could think of 
1. Point anchor tag to nothing `<a href="#"></a>` (which has to be changed in messages.properties file for each locale)
2. Add `{cursor:pointer;}` style in the [userbar.less](https://github.com/mozilla/thimble.mozilla.org/blob/master/public/resources/stylesheets/userbar.less) for `a.navbar-login:hover`

I hope I am going in the right direction. :)

**Comment by gideonthomas** [comment] 2016-06-26 16:59
Oh nice! You seem to have figured out the solution quickly! I think option 2, i.e. editing style rules, is a cleaner (and easier) approach so I would go with that!

Once you've made the change and tested it, feel free to open up a pull request against the `master` branch of this repository and someone from our team will review it ASAP.

**Comment by gideonthomas** [comment] 2016-06-27 15:41
Fixed with e63d9c02679bca361cacae913ef06876a376718b

**Closed by gideonthomas** 2016-06-27 15:41 UTC
Labels: good first bug
