### ISSUE TITLE
Students are getting 404 File Not Found errors on Preview; refreshing does not seem to help

### ISSUE THREAD

**Issue by mrcottington** [mozilla/thimble.mozilla.org#2567] opened 2017-11-28 14:26 UTC
Hello,

I teach high school CS and we are using Thimble for web design. We are experiencing problems with a few students who consistently see this error in the Preview:

404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: bramble/production/dist/vfs/708428/projects/1321821/index.html
RequestId: EA755CCC32BD09CD
HostId: Pc488FKw/szlSuT2kxY0A0TR0HZvdsoc6+7Dnl1T4YR/DnTwLaFiMCueboQy+h6rM2RhqIB/fgU=
An Error Occurred While Attempting to Retrieve a Custom Error Document

Code: NoSuchKey
Message: The specified key does not exist.
Key: error.html

It's only a few students and it is consistent if they make new projects, refresh the page, or even make new accounts. We use Chromebooks that are school managed, but 95% of students are unaffected - it's just a handful. Thanks for the help!

**Comment by humphd** [comment] 2017-11-28 17:20
@mrcottington I'm sorry to hear that you're struggling with this.  We shipped a fix for this problem last week, but it sounds like there is yet another edge case we haven't dealt with thus far.

The problem is that we use a Service Worker to create a web server inside the web browser.  However, certain browser settings can disable service workers from installing (e.g., disabling third-party cookies) in iframes--ours runs in an iframe on a separate origin in order to isolate potentially hostile user-written JS from the rest of the app.

There is a manual work-around you could try on those few machines.  If you append `?cacheType=blob` to your Thimble URLs, it will force the app to skip the service worker code and load in a fall-back mode.  For example:

```
https://thimble.mozilla.org/?cacheType=blob
...
https://thimble.mozilla.org/en-US/anonymous/4578752b-6800-4ea2-acc0-61a6fe7ef205?cacheType=blob  
```

Doing so might be enough to get those students to load the app and keep working.  This might then trigger the update to kick in, and install our new code, which should alleviate the need for this manual trick.

If it doesn't, I'd be interested to know what you see, and maybe we can debug things here and get another fix in place.

cc @flukeout

**Comment by flukeout** [comment] 2017-11-28 17:27
I've got a few questions

* Have these problems been happening in the past, or is this something new?
* Do all of the Chromebooks have the same privacy & security settings, or are they different?
  * In Firefox, disabling third-party cookies caused Thimble to break
* @mrcottington Are you able to get a screenshot of anything that is going on in the browser console when you get these errors?
  * If you're not sure how, [here's a guide](https://github.com/mozilla/thimble.mozilla.org/wiki/Checking-the-browser-console-for-errors)

@humphd do you think it's wroth seeing if unregistering the Serviceworkers via dev tools might resolve this?

**Comment by mrcottington** [comment] 2017-12-03 21:53
Hey all,

Sorry for the delay in responding - but thank you immensely for the assistance. Adding ?cacheType=blob did in fact work, so that has been awesome. In terms of your questions....

-This is my first time ever using Thimble (either by myself or with students) but according to our other CS teacher who used it in his class last year, this is a new problem.

-They do have all the same privacy and security settings to the best of my knowledge. They are pretty strict settings so there might be something in there making issues happen.

-I can try to get a screenshot this week if it happens again. 

For now though, it appears the manual workaround solution is working. Thanks again!

**Comment by humphd** [comment] 2017-12-04 19:19
That's great to hear, @mrcottington, thanks for letting us know.  I'm going to close this, but please file any followups to other issues you hit.

**Closed by humphd** 2017-12-04 19:19 UTC
Labels: support
