### ISSUE TITLE
Bramble and Brackets LiveDev errors

### ISSUE THREAD

**Issue by mklilley** [mozilla/thimble.mozilla.org#2599] opened 2018-01-17 14:15 UTC
Hi.

I'm getting some strange stuff logging to the console. Also getting some bramble errors.

![screen shot 2018-01-17 at 14 13 22](https://user-images.githubusercontent.com/7937044/35047068-c264325e-fb90-11e7-9088-f111d844c54b.png)

Last time I used Thimble was back in September so I am wondering whether something was introduced since the which created what appears to be a bug.

Thanks

**Comment by humphd** [comment] 2018-01-17 17:16
That error is coming from https://github.com/mozilla/brackets/blob/master/src/LiveDevelopment/MultiBrowserImpl/protocol/remote/LiveDevProtocolRemote.js#L352

I suspect that this is our live dev preview script injecting failing on finding a `</head>` to use as an insertion point.  We inject a bunch of scripts that let the editor communicate with the running preview page and vice versa over `postMessage`.  There are two places where this happens:

* https://github.com/mozilla/brackets/blob/master/src/LiveDevelopment/MultiBrowserImpl/language/HTMLInstrumentation.js#L806-L830
* https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/nohost/HTMLServer.js#L165-L182

I haven't tested this, but I suspect it's one of those.  Question: does your page's script do any `postMessage`?  I wonder if we're catching something you're sending, and failing to parse it somehow?

**Comment by mklilley** [comment] 2018-01-18 07:58
Hey. Thanks for replying so quickly. When you say page's script which script you do mean? If you look at the HTML code from my screenshot I only have an HTML tag - no scripts referenced. Thanks again, Matt

**Comment by humphd** [comment] 2018-01-18 19:30
Indeed, I was thinking out loud when I wrote that, but obviously you're not including any scripts.  I still suspect it's one of the issues I mentioned above.

**Comment by gideonthomas** [comment] 2018-01-18 21:10
@humphd it's interesting that `msgStr` is an object there. So somehow the message that the function is receiving is an object not a string and that's why it's throwing.

**Comment by humphd** [comment] 2018-01-19 16:36
@mklilley I'm unable to reproduce what your'e seeing above.  Is it possible that you got into this state by originally having a page that called one or both of those scripts in your project, and then deleted everything but the enclosing `<html></html>` tags?  I ask because I wonder if this error is due to a previous state of the preview window vs. the one that would currently render.

**Comment by mklilley** [comment] 2018-01-21 10:44
Hey @humphd Your instinct is correct this is exactly what i did. However there were no scripts being used before.

I also get the same thing happen when i start a brand new project.

Ah, literally as I was just taking the screen shot I realised something when i looked at some of the details of the errors - they match my ethereum address. I have MetaMask installed on Chrome so it must be interacting with thimble in a strange way.

Sorry, this doesn't appear to be a Thimble issue after all. Sorry for wasting your time.

Matt

**Comment by humphd** [comment] 2018-01-21 17:56
@mklilley this is good, thanks for the extra info.  I think we should still fix this, since people are going to have lots of extensions installed, some of which might do things like you're seeing.  We should harden our message passing code between the editor and live dev windows so we ignore stuff like this.

The fix is probably to do some kind of inspection [here](https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/PostMessageTransport.js#L108) before we send this on to the general transport parsing code.  @gideonthomas, make sense?

**Comment by gideonthomas** [comment] 2018-01-24 20:27
hmm, yeah. I wonder if we can just change this to messagechannel postmessage so that the communication is over two ports (editor and preview) and no other messages will be listened to.

**Comment by humphd** [comment] 2018-02-02 16:55
I've got a fix up in https://github.com/mozilla/brackets/pull/921 @gideonthomas

**Comment by humphd** [comment] 2018-03-06 16:07
@gideonthomas has this landed on prod?  If so, let's close.

**Closed** 2018-03-06 20:01 UTC
Labels: brackets, bug
