### ISSUE TITLE
wishlist: thumbnail of project on 'my projects' page

### ISSUE THREAD

**Issue by bfalchuk** [mozilla/thimble.mozilla.org#1905] opened 2017-03-21 13:45 UTC
It would be great if the "My Projects"  list showed something more about the project than the title and timestamp - in particular, a thumbnail of the project's main html page would be great.

**Comment by jgmac1106** [comment] 2017-03-21 15:08
Hey @bfalchuk this is a common request and is being discussed in a previously filed issue #1628 and a few others.

**Comment by humphd** [comment] 2017-03-21 16:52
Agreed, we should do a version of this.  I'm going to close this issue as a duplicate of #1628, since there is already discussion happening there.  @bfalchuk please add your voice to that issue.  Thanks for filing this.

**Closed by humphd** 2017-03-21 16:52 UTC
