### ISSUE TITLE
Uncaught TypeError: Cannot read property 'EDITOR_UI' of undefined - analytics.eventCategories

### ISSUE THREAD

**Issue by edyedy123** [mozilla/thimble.mozilla.org#2006] opened 2017-04-19 20:20 UTC
When changing dark/light themes you get an error.
![other](https://cloud.githubusercontent.com/assets/16922991/25200349/0250ec00-251c-11e7-8d9d-4094f3bfb1c4.gif)

bramble-menus.js:195 Uncaught TypeError: Cannot read property 'EDITOR_UI' of undefined
      at HTMLDivElement.toggleTheme (bramble-menus.js:195)
      at HTMLDivElement.dispatch (jquery.js:4435)
      at HTMLDivElement.r.handle (jquery.js:4121)

**Comment by humphd** [comment] 2017-04-20 15:40
I can't reproduce this bug on staging https://bramble.mofostaging.net/, which runs latest master.  Are you sure your tree is up to date?

**Comment by edyedy123** [comment] 2017-04-21 02:00
I re installed thimble and I don't see the error anymore.

**Comment by humphd** [comment] 2017-04-21 20:12
Re-opening, as this is being hit by @rajat-dhyani as well, only in `bramble-ui-bridge.js`.  I wonder if it's a load-timing bug.

**Comment by humphd** [comment] 2017-04-21 20:14
@gideonthomas what do you think of this?  It's happening with https://github.com/mozilla/thimble.mozilla.org/blob/9ec47c9937ad362de55d6c825c78c000c984c949/public/editor/scripts/editor/js/fc/bramble-ui-bridge.js#L285 too.

**Comment by humphd** [comment] 2017-04-21 20:32
![image](https://cloud.githubusercontent.com/assets/427398/25294892/2e8696e6-26af-11e7-94dd-edcdf64b3c27.png)

Here you can see that the `analytics` object *does* exist, and has something called `event` on it; but it also has `conversionGoal`, which points to it being the wrong module.

@flukeout did you remove an `npm` module to add this?  Is it being picked up incorrectly for some people?

**Comment by humphd** [comment] 2017-04-21 20:34
Possibly related commits, that might be missing in each of these cases:

* https://github.com/mozilla/thimble.mozilla.org/commit/6c531fd4c5fafe6dd62cbe91584cef52f6cd62c7
* https://github.com/mozilla/thimble.mozilla.org/commit/da5b198f7aa933d975659851913d92e3ab127314

**Comment by flukeout** [comment] 2017-04-21 20:34
Yeah, we removed the reliance on the old ``webmaker_analytics`` module and added the code directly into the codebase.

**Comment by humphd** [comment] 2017-04-21 21:55
@Rajat-dhyani reports that blowing away `node_modules/` and reinstalling fixes things.  I think this is not an on-going bug we need to keep open, but it's good to have the facts in here for others who might hit it.  Closing.

Thanks for helping debug it @Rajat-dhyani, and sorry you had to waste time on it.

**Closed by humphd** 2017-04-21 21:55 UTC

**Comment by Rajat-dhyani** [comment] 2017-04-22 05:02
@humphd anytime sir 👍
