### ISSUE TITLE
Blank language option in Languages menu.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1963] opened 2017-04-06 21:33 UTC
![image](https://cloud.githubusercontent.com/assets/25212/24776518/fa36da34-1ad5-11e7-8c4a-033868ab355d.png)

**Comment by bkim49** [comment] 2017-04-07 16:41
Hello, I was looking into this bug. Apparently the missing language name is Tajik according to google.

![image](https://cloud.githubusercontent.com/assets/17182037/24809504/b41fdb96-1b8d-11e7-91a0-ebdca109c449.png)

I also looked at the userbar.html, and it uses javascript code to generate the language texts while it loads. 
There was #1950 issue that is related to this bug. Maybe it could be something they could fix.

**Comment by gideonthomas** [comment] 2017-05-10 06:13
Dupe of #1950 (thanks for noticing that @bkim49), closing!

**Closed by gideonthomas** 2017-05-10 06:13 UTC
Labels: bug
