### ISSUE TITLE
Preview autoreload lags JavaScript editing

### ISSUE THREAD

**Issue by combojs** [mozilla/thimble.mozilla.org#2591] opened 2018-01-08 14:44 UTC
I'm not sure if this would be a feature request or UI issue, but there is a delay when Thimble autosaves. Most times I think JavaScripts are not working when I make changes, and have to remind myself that saves are not immediate.

I was wondering if a "force save" or "save" button could be added.

**Comment by humphd** [comment] 2018-01-08 16:37
@combojs we have some other bugs on this, so you're not alone.  The issue is that JS has to be fully re-parsed/executed when there are changes on disk vs. what we do with CSS where we can dynamically replace and inject things as you type.  Our saving logic autosaves every 5 seconds right now, and then that will force a reload of the preview.  No matter what we do for an autosave time, there will be lag, and having it reload too often will cause flickering and annoying hangs as the JS is wrong while you type.  In another bug we've discussed putting an overlay on the preview to let you know that it's out of date and needs a refresh.  Maybe we should do that.

As a workaround, you can actually force a save with CTRL+s (Win/Linux) or CMD+s (Mac).

**Comment by humphd** [comment] 2018-01-08 16:39
https://github.com/mozilla/thimble.mozilla.org/issues/2303 is one of the bugs I'm thinking of, but there's another one I can't find at the moment.

**Comment by gideonthomas** [comment] 2018-01-08 17:54
Closing as a duplicate.

**Closed by gideonthomas** 2018-01-08 17:54 UTC
