### ISSUE TITLE
Pages reverting to an empty/earlier version in Thimble resulting in data loss

### ISSUE THREAD

**Issue by flaki** [mozilla/thimble.mozilla.org#1471] opened 2016-04-18 18:36 UTC
So this is a pretty weird and rather unfortunate issue we have came across at least two times in the last weeks, but I've never been able to reproduce it until now.

The problem manifests with documents in the Thimble editor reverting to earlier versions, or even the "empty" (newly created) files. This almost always goes for HTML files (never seen it happen to other files), also usually secondary files (`index-n.html`) but now it happpened to a primary file (that is, `index.html`).

If one with access has a look at [one of my Timble makes, id #175177](https://thimble.mozilla.org/en-US/user/flaki/175177), it could be seen it's a much shorter (I'd guess, earlier) version of the files (`index.html` in particular). The file is a mere 47 lines, while currently published version of the file clocks in at 130+ rows. The *Publish* button itself shows that the file hasn't been modified since it was published (doesn't offer updating the published version, but *Unpublish* only), and Thimble says the file was last modified 8 days ago.

We have tried publishing the project on earlier occasions, which confirms the data loss (current version is published, and the "more recent" published version is lost forever). I was able to recover my code from its current published version, but others before weren't that lucky. Needless to say this has resulted in some pretty rough experiences and comments towards Thimble (which people otherwise tend to like much).

I can share one such other project, should that help debugging this issue ([this is the project](https://thimble.mozilla.org/en-US/user/gbarni/176812), [published here](https://thimbleprojects.org/gbarni/52622/) ).

**Comment by humphd** [comment] 2016-04-18 18:44
It sounds like we don't have a sync event in the queue for the file, and it's overwriting it with what's in the project's tarball (last-known-saved) from the server.  I remember this, but can't remember the details--I feel like we solved it.  I wonder why this would happen now.

It *could* be the result of the save having failed to the server (publish server crapping out for some reason, maybe overload) and the save sync event getting cleared when it shouldn't have, thus losing the current dirty version of the file.

cc @cadecairos.  Do we have info on the publish server breaking recently?

@gideonthomas, what do you think?

**Comment by cadecairos** [comment] 2016-04-18 19:31
On April 13th, the publish servers got overloaded, and several hundred requests that hit the database timed out. I've seen a couple spikes since then, maybe 2-3 timeouts per day since then.

Based on my analysis of the RDS metrics, we're experiencing 40+ concurrent write requests to the database, resulting in high CPU usage & ~2MB/second of writes to disk. Requests start backing up and if it takes longer than 30 seconds to respond, Heroku drops the connection.

**Comment by gideonthomas** [comment] 2016-04-18 19:44
@cadecairos can we increase the pg request timeout duration on heroku?

**Comment by Pomax** [comment] 2016-04-18 19:45
that feels like passing the buck - all you're doing is making it take slightly longer to still guaranteed fail under heavy load.

**Comment by cadecairos** [comment] 2016-04-18 19:48
No, there's no way to increase the 30 second timeout restriction imposed by the Heroku router

**Comment by cadecairos** [comment] 2016-04-18 19:50
We might want to consider creating one or two read replicas to distribute the query load

**Comment by flaki** [comment] 2016-04-18 20:21
Let me clarify just one more thing. To my best knowledge (I'm not 100% sure of this, but pretty sure), the publish went out okay, and I could access my files later. Again, I'm not 100% sure that I opened the project in a different browser/device, but I'm pretty sure.

Can anything cause something like that, pages "regressing" to a previously saved version? As this seems more consistent to me as to what the issue _seems_ to be at least.

Also, in any case, the current UX is no good, if it fosters the false assumption that the user's project has been saved (the published page reassures this belief), but the user find their project later in a wildly different state. :disappointed:

**Comment by gideonthomas** [comment] 2016-04-18 21:59
possibly related (just on a different scale) https://github.com/mozilla/thimble.mozilla.org/issues/1465

**Comment by gideonthomas** [comment] 2016-07-08 16:02
Since we think this is a load issue on publish, this will probably help: https://github.com/mozilla/publish.webmaker.org/issues/233

**Comment by mrcallaghan** [comment] 2016-10-03 19:05
I have a class of 20 Web Design students and we had a similar issue happen to about 5 students today.  They worked on a project over the weekend only to find their project reverted back to an earlier state today.  All of their work from the weekend is seemingly gone.  Has there been an update or fix to this issue.  We will have to abandon Thimble if a fix is not available.

**Comment by gideonthomas** [comment] 2016-10-04 15:00
@mrcallaghan sorry to hear about the data loss. We will be investigating what might be causing the problem but any information that you can provide about your scenario will be helpful; for e.g. were the students logged into their account before and after the data loss, were the projects published, how much data was lost (one file, multiple files), any other information that you think might be useful to help us debug the issue.

**Comment by mrcallaghan** [comment] 2016-10-04 18:50
@gideonthomas The students noticed the data loss when they lagged into Thimble at school.  They were logged in at home working on their projects and all appeared OK to them.  None of them had published that I'm aware of.  Here are some details I was able to gather today:

user rsfang lost work on both html and css files from the weekend, but the images he uploaded at home work fine.

user rhea-singh worked on a page and none of the html saved, but css did.

user zacharykaeding lost just part of his html file (the footer) and was able to reproduce the error a second time (shared a video with me of him coding footer to prove it).  Attached is an image of the 'lost' footer.  There should be a link inside this footer where it is black.
![the picture of the webpage when i login on school](https://cloud.githubusercontent.com/assets/21110291/19087568/190f05e6-8a38-11e6-9ac1-3bb6eb300e7d.JPG)

**Comment by cadecairos** [comment] 2016-10-04 19:08
We should try reproducing this using the same account on *different* machines

**Comment by humphd** [comment] 2016-10-04 19:10
I wonder if we have a sync-race issue, where the project is 1) open at home; 2) open at school; 3) updated at school; 4) overwritten by what's at home.

**Comment by gideonthomas** [comment] 2016-10-13 19:57
Migrating to https://github.com/mozilla/thimble.mozilla.org/issues/1564

**Closed by gideonthomas** 2016-10-13 19:57 UTC
