### ISSUE TITLE
"Type Error: m is undefined" crash on startup with Firefox

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/thimble.mozilla.org#2124] opened 2017-05-15 21:21 UTC
**Context**
I am trying to create a project, following the instructions that were given to us in the doc. I am using Firefox in a Mac.

**Expected Result**
I expected to see the dashboard to start my project

**Current Result**
![thimble](https://cloud.githubusercontent.com/assets/22157921/26080067/c7bcea0e-3979-11e7-93fc-26523c0aa3de.gif)

**Comment by cadecairos** [comment] 2017-05-15 21:48
@taisdesouzalessa Was your browser in private browsing mode?

**Comment by taisdesouzalessa** [comment] 2017-05-15 22:05
@cadecairos nope :(.

**Comment by gideonthomas** [comment] 2017-05-15 23:04
@taisdesouzalessa would you be able to open dev tools and copy/paste whatever you see in the console?

**Comment by taisdesouzalessa** [comment] 2017-05-15 23:25
Sure @gideonthomas. Does this help? 
<img width="1268" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/26083485/fcee5bca-398a-11e7-8a80-31004ad521dd.png">

**Comment by humphd** [comment] 2017-05-16 15:13
I've encountered this before, and every time I've had to reload 2 or 3 times to fix it. Somehow it's cache related, perhaps with a mismatch of what's coming from cloudfront, what's in service worker cache, what's in browser cache, etc.  I also only see it in Firefox, which is what is happening here too.

I'm not sure what we should do here.  I'm pleased to see that the changes we made to give a Reload button on the error page are working.  I think the only action that can solve this is reloading.

**Comment by cadecairos** [comment] 2017-05-16 15:21
Would it be worthwhile adding an FAQ link to the page to describe troubleshooting steps for that situation (i.e. clear browser cache on FX, Edge, Chrome, Safari)? Presuming that clearing the cache will help in this case.

**Comment by humphd** [comment] 2017-05-16 15:25
We rewrote `Reload Now` to force a server-side refresh (vs. browser cache) which should be as good as going into Dev Tools.  We've found that most users find doing the "clear cache" dance difficult.

**Comment by flukeout** [comment] 2017-05-19 22:01
To add to this, no amount of clearing the browser storage on her machine via dev tools helps. The only way to resolve this is to create a new Firefox profile, which I'm guessing creates a new IndexedDB.

Here is more detail from the console log when this happens.

![image](https://cloud.githubusercontent.com/assets/25212/26268325/c1577d14-3ca3-11e7-9743-f2fea4c75a4a.png)

It just can't open IndexedDB at all it seems.

In addition, we just spent a bunch of time on mattermost trying to troubleshoot this very error with a teacher and a class of students. Many were seeing this error on Chrome. Because these were public school computers, we weren't able to get access to the browser console, so we're somewhat in the dark.

I'm guessing the Chrome indexedDB is getting corrupted also, or is somehow unreachable. The teacher reported that this happens intermittently, and wasn't happening a couple of days ago, so it's not anything like the browser settings or add-ons that might be conflicting with something we're doing.

cc @humphd 

cc @cadecairos @Pomax - drop some extra info here if you have anything to add.

**Comment by flukeout** [comment] 2017-05-19 22:43
In addition, I just tried copying tais' indexed db into my own Firefox profile to see if I could reproduce what she is seeing. I couldn't, I think the first load failed, but a reload made things work just fine.

**Comment by humphd** [comment] 2017-11-20 14:26
Closing now, as we haven't seen this again in a while.

**Closed by humphd** 2017-11-20 14:26 UTC
Labels: QA
