### ISSUE TITLE
Consider ditching the 'light' theme?

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2359] opened 2017-07-11 22:52 UTC
Do we need both themes? It adds a lot of extra work when adding new features. Here's what the analytics say for a month of use. This is the Theme Toggle event...

![image](https://user-images.githubusercontent.com/25212/28094281-941e42f2-6650-11e7-9366-529da3240448.png)

This event only fires when someone toggles the theme, so the way I read it like this:

* The light theme was turned on 7,200 times
* The dark theme was turned on 6,000 times
* So, that means the light theme was left on 1,200 times total

In that same timespan, we had 77,600 users. Meaning that even if every switch to the light theme was from a unique user, less than 2% of all users are using the light them.

cc @humphd @gideonthomas @Pomax - what do you all think?

**Comment by ryanwarsaw** [comment] 2017-07-12 03:35
I'm rather curious as to what the extra work could be in terms of adding new features? Do we need to provide two different variations of a features CSS for both themes? Is there a way that we can reduce the amount of work required to add support for this?

I personally quite like using light themes, although understandably a large portion of users prefer dark themes, it can make it a much nicer reading / viewing experience especially with long usage.

I think it would be a cool feature if we (or whomever eventually maintains Thimble) implemented a way for users to adjust the theme and create their own themes, much like many modern code editors and development environments allow them to do. Perhaps out of scope of this issue, but worth considering if our goal here is to remove interoperability of themes.

**Comment by flukeout** [comment] 2017-07-12 16:13
It's just a matter of adding additional styles for the other-colored theme. Generally I start with the light theme and then add styles for the dark one. One of the issues is that within the different extensions, we don't have access to a master stylesheet, each extension has it's own stylesheet so I feel like there is a lot of duplication going on.

It would be great to move some of the shared styles higher up somewhere so we could make global changes more easily.

**Comment by humphd** [comment] 2017-07-12 17:20
What about the issue of printing and on-screen contract being crappy?  The light theme helps make this better.  If we could retain the positive aspects of this, I'd be happy to go this route.

**Comment by Pomax** [comment] 2017-07-12 17:45
Also, what about the issue of people with visual disabilities who don't do well *at all* on dark themes, and can only really read what's going on with dark text on light backgrounds? 

If the issue is "extra work", let's figure out how to automate that work rather than removing an important option for people who would otherwise be locked out of Thimble because of a choice made by able-sighted devs =)

**Comment by flukeout** [comment] 2017-07-12 18:18
Yeah, making it easier to do the theming would be great. We should also address printing in a separate issue, much of what's on the screen doesn't need to be printed properly. 

Am curious about the accessibility angle - do you have any references to back up that a light theme is better in that regard @Pomax ?

Closing this issue though - thanks all for chiming in.

**Closed** 2017-07-17 20:26 UTC
Labels: Needs Discussion
