### ISSUE TITLE
[Firefox] Autocomplete for colours has bad spacing

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2337] opened 2017-06-22 21:56 UTC
![screen shot 2017-06-22 at 5 54 54 pm](https://user-images.githubusercontent.com/427398/27457800-0d556e7a-5774-11e7-9cab-69ed56a4ee01.png)

vs. Chrome:

![screen shot 2017-06-22 at 5 56 15 pm](https://user-images.githubusercontent.com/427398/27457821-1e955ed4-5774-11e7-955d-5ecb4edbbbd9.png)

**Comment by dsych** [comment] 2017-08-29 21:01
@humphd the problem is in how chrome and firefox process the "::before" tag in this case. Firefox puts it before the swatch and chrome - after. What is the ::before tag supposed to align?

**Comment by dsych** [comment] 2017-08-29 21:12
I was able to make it appear the same on both firefox and chrome.


![firefox](https://user-images.githubusercontent.com/16144679/29844387-1a6da732-8cdd-11e7-9a5f-336e5671dde7.png)

**Comment by gideonthomas** [comment] 2017-09-05 15:47
wow yeah that's a pretty weird hack they've got there - using a pseudo-element for alignment. @dsych, your screenshot looks great (maybe add a little more margin before the text?). Do you want to open up a PR for that and @flukeout can take a look at it?

**Comment by gideonthomas** [comment] 2017-09-06 23:41
Fixed in 8ae1c8c3f07491b2e790fff7863358d70995dbc8 Thanks @dsych!

**Closed by gideonthomas** 2017-09-06 23:41 UTC
Labels: brackets, UI
