### ISSUE TITLE
Add "Courier New" font

### ISSUE THREAD

**Issue by JosefJezek** [mozilla/thimble.mozilla.org#2552] opened 2017-11-09 13:22 UTC
Courier font used in `.CodeMirror` is not monospaced on Linux - Ubuntu. :-(

Code with Courier font
![image](https://user-images.githubusercontent.com/2110319/32607401-2c14427a-c559-11e7-8ae4-b23f2684604b.png)

Code without Courier font - used generic `monospace` font
![image](https://user-images.githubusercontent.com/2110319/32606830-128c0358-c557-11e7-9f2d-bf18f5bc9144.png)

On page is here...
```
<style type="text/css" id="codemirror-dynamic-font-family">.CodeMirror{ font-family: 'Menlo Regular', Consolas, Inconsolata, 'Vera Sans', 'Lucida Console', Courier, monospace, fixed }</style>
```

Courier font is defined in this file
https://github.com/mozilla/brackets/blob/master/src/styles/brackets_fonts.less#L87

Courier is also here
https://github.com/mozilla/thimble.mozilla.org/blob/00a85b9ff8c5669276c607ec6b38252d4e47c970/public/editor/stylesheets/editor.less#L471

https://developer.mozilla.org/en-US/docs/Web/CSS/font-family

**Comment by Pilabio** [comment] 2017-11-16 10:12
Hi @JosefJezek, I'm a newbie github user and would like to help this issue, still I have some newbie questions to make before taking it, if you could help me. So the issue is just to add the font "Courier new" to the css code? Or this have to do with some bug that makes the font looking different?

**Comment by Pilabio** [comment] 2017-11-16 10:32
Hi @JosefJezek. So the issue is just to add the font "Courier new" to the css code? Or this have to do with some bug that makes the font looking different?

**Comment by gideonthomas** [comment] 2017-11-23 20:42
@Pilabio, it looks like the Courier font does not render well on browsers in Linux environments. We use Courier to display text in Thimble and Brackets. This issue is to change Courier to Courier New so that any text that appears in Thimble and Brackets is shown correctly.

**Comment by gideonthomas** [comment] 2017-11-23 20:43
And it looks like this issue has been fixed, closing.

**Closed by gideonthomas** 2017-11-23 20:43 UTC
Labels: Assigned to Contributor
