### ISSUE TITLE
Unable to export project (.zip) in Firefox.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1710] opened 2017-02-08 18:43 UTC
When attempting to export a zip of a project, I'm seeing this in the console...

![image](https://cloud.githubusercontent.com/assets/25212/22751935/64e94b0e-edeb-11e6-88e3-a4bbd1259cf4.png)

Works fine for the same project in Chrome.

cc @gideonthomas @humphd

**Comment by humphd** [comment] 2017-02-08 19:06
Dupe of #1595

**Closed by humphd** 2017-02-08 19:06 UTC
Labels: bug
