### ISSUE TITLE
Fix Chromebook quotation display

### ISSUE THREAD

**Issue by chadsansing** [mozilla/thimble.mozilla.org#1536] opened 2016-08-10 16:06 UTC
A user guiding teachers through Thimble noted that on their Chromebooks, Thimble interpreted both parts of double- and single-quotation mark pairs as closing quotations, breaking attribute values. We should make sure Thimble interprets opening and closing quotation mark keystrokes differently on Chromebooks or provide an easily discoverable work-around.

**Comment by gideonthomas** [comment] 2016-08-10 16:07
@chadsansing was the code copy/pasted from a document or a text editor?

**Comment by chadsansing** [comment] 2016-08-10 16:16
No, but the work around was to copy and paste quotation marks that were already inside a remixed project and facing the right directions.

**Comment by Pomax** [comment] 2016-08-10 21:27
what do chromebooks do? Do they not simply yield ascii character 34 (`"`) in the editor?

**Comment by humphd** [comment] 2016-08-10 21:30
Can we get some example text?  A Chromebook is just Chrome, so I'm surprised this is an issue.  Is this a case of mixing single- and double-quote?

**Comment by chadsansing** [comment] 2016-08-11 10:20
I'll ask for more documentation.

**Comment by khanh2003** [comment] 2016-08-14 02:15
maybe
```
<input type="...">
<input type=“…”>
```

**Comment by humphd** [comment] 2017-01-24 18:49
NOTE: we have 3 Chromebooks in CDOT, if someone at Seneca wanting to work on this needs one to test with, just come see me.

**Comment by Blackweda** [comment] 2017-01-27 18:19
Can I take a try at this one??

**Comment by humphd** [comment] 2017-01-27 19:34
@Blackweda, sure, it's yours.  If you want to borrow a ChromeBook from me, let me know on Tuesday.

**Comment by Blackweda** [comment] 2017-02-10 04:59
@chadsansing 
I'm using a Chromebook to test your bug issue.. and I used the following code:

<input type="button" value='Yes'>                           Works
<input type='button' value='Sometimes'>               Works
<input type="button' value='No">                           Faulty syntax, expected error(type="buttonvalueno")
<input type='button" value="Maybe'>                     Faulty syntax, expected error
<input type="button" value='Yes?'>                         Different style - still works

So far, it seems if I use consistent usage of quotation marks, whether single or double (on opening and closing a quotation), Chrome understands my point. We need an actual example to test please?

**Comment by chadsansing** [comment] 2017-02-10 11:05
Thank you, @Blackweda - our user didn't capture the bug in this case; only reported it. Might be time to close this one?

**Comment by gideonthomas** [comment] 2017-02-11 01:37
If we can't reproduce this issue, let's close it for now and reopen if it's reported again.

**Closed by gideonthomas** 2017-02-11 01:37 UTC
Labels: assigned to contributor, good first bug
