### ISSUE TITLE
Cmd on Mac triggers an unindent

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1572] opened 2016-11-01 18:03 UTC
Whenever I press the Cmd key on a tag, it unindents the line. Don't know if anyone else is having this issue.

**Comment by flukeout** [comment] 2016-11-08 00:34
Can we escalate this? I tried to do some work today on the Back to School postcard and this was infuriating (and also leads to terribly indented code unless you have extreme patience).

@Pomax Do you run windows still? Can you check this and see if it happens with the control key by chance?

**Comment by gideonthomas** [comment] 2016-11-08 00:37
@flukeout I tried this on Windows, it doesn't happen on Ctrl. Yeah lol I was having a hard time creating projects. I'll try to work on this tomorrow.

**Comment by humphd** [comment] 2016-11-08 16:24
I dug into this, and it's (maybe) not a bug or a new regression--I tried bisecting and it goes back forever.  Apparently Brackets is configured to map `CMD+[` to `indent` and `CMD+]` to `unindent` (it uses `CTRL` vs. `CMD` on Windows/Linux for this same function).  This is a keybinding that comes from https://github.com/codemirror/CodeMirror/blob/06431f4d7eb24b0945bc7bb0b775a4f644766c64/CHANGELOG.md#2230-2012-03-26 and is wired into Brackets here: https://github.com/adobe/brackets/blob/master/src/base-config/keyboard.json#L94-L103

When you have your cursor in the middle of an element name, it highlights the element (and it's matching/closing partner, if any) and then pressing left CMD triggers `CMD+[` and pressing the right CMD triggers `CMD+]`.  I suspect this is happening because there is a selection on the line, so it's doing indent/unindent.

We could correct this a few ways:
* delete the default keybindings for `Ctrl+[` and `Ctrl+]` in `src/base-config/keyboard.json`.  This works, but it also seems somewhat heavy-handed; though, maybe we don't care?
* write an extension that overrides these two keybindings for Bramble.  Seems like a bunch of work to me.
* Try to hook into Bracket's built-in keyboard mapping overrides.  There is actually code for doing this, but it depends on stuff we don't use (e.g., loading the user's keymap preferences JSON file from their profile dir).  We'd have to fake this somehow.  Again, seems like a make-work project to me.

What do you think, should I just yank those two keybindings and be done with it?  I can't think that our users care about having this--none of us even knew they existed, so how will a beginner?

**Comment by flukeout** [comment] 2016-11-08 17:49
Thanks for looking into this. I'd say in the short term we nuke those bindings. I'm really disliking using the editor right now. In my day-to-day editor I actually use the ``Command+[/]`` combo, but not sure how common that is.

So for this thing here...

```
  "edit.indent":  [
        {
            "key": "Ctrl-]"
        }
    ],
```

...is there another spot that triggers it from just the Command / Control key?

**Comment by flukeout** [comment] 2016-11-08 18:04
I [found this](https://github.com/adobe/brackets/search?utf8=%E2%9C%93&q=_macReservedShortcuts&type=Code )

```
        _macReservedShortcuts = ["Cmd-,", "Cmd-H", "Cmd-Alt-H", "Cmd-M", "Cmd-Shift-Z", "Cmd-Q"],
```

It's the only reference to a Cmd key without any additional keypresses, so I wonder if the ``Cmd-`` part is somehow causing something to misfire. I'll try it out once I get my dev env set up.

**Comment by humphd** [comment] 2016-11-08 18:08
As I mentioned above, the issue seems to be the fact that it auto-selects the element name, and then CMD becomes CMD+[.  I think this happens deep in CodeMirror.

I'll do a patch to remove those two keybindings in Brackets.

**Comment by gideonthomas** [comment] 2016-11-08 18:09
@humphd any chance that it's easy to change to `Shift+Tab` and `Tab`?

**Comment by humphd** [comment] 2016-11-08 18:12
@gideonthomas what are you asking for exactly?  You can see the default CodeMirror bindings here: https://codemirror.net/doc/manual.html#keymaps and if you search for Tab and Shift-Tab, you'll see what it does by default.  Yes, we can override this stuff to a point.

Please put all your hopes and dreams for keybindings into a comment here, and I'll do it in one patch.

**Comment by gideonthomas** [comment] 2016-11-08 18:23
Ah sorry, nvm, it already does what I want. @humphd yeah, just removing those keybindings in Brackets should be enough.

**Closed** 2016-11-09 19:51 UTC
Labels: brackets, bug, P1
