### ISSUE TITLE
QA > "Open Issues" indicator is wrong on Get Involved page

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2125] opened 2017-05-15 21:22 UTC
Indicator shows 30 in the little bubble...

![image](https://cloud.githubusercontent.com/assets/25212/26080091/e6310998-3979-11e7-8788-2aa453c35581.png)

But github at the time shows 49 open issues with that label...

![image](https://cloud.githubusercontent.com/assets/25212/26079977/7f9eafe6-3979-11e7-8737-dcd022e354c7.png)

**Comment by humphd** [comment] 2017-05-16 15:56
Dupe of #2135, closing.

**Closed by humphd** 2017-05-16 15:56 UTC
Labels: QA
