### ISSUE TITLE
Fullscreen preview is not possible to close

### ISSUE THREAD

**Issue by iBobik** [mozilla/thimble.mozilla.org#1477] opened 2016-04-29 10:36 UTC
![snimek obrazovky 2016-04-29 v 12 30 55](https://cloud.githubusercontent.com/assets/614232/14913850/48a11a5a-0e06-11e6-8155-f2cdf1265c09.PNG)
Safari 9.1 (11601.5.17.1)

Button is there, but is not visible:
![snimek obrazovky 2016-04-29 v 12 32 28](https://cloud.githubusercontent.com/assets/614232/14913955/bf16ffd8-0e06-11e6-95a5-caccb3e9e867.PNG)

When I disabled `width: 90px !important;` on `.preview-pane-nav` it will appear:
![snimek obrazovky 2016-04-29 v 12 34 09](https://cloud.githubusercontent.com/assets/614232/14913963/ca8fed2a-0e06-11e6-852e-d645ee9a3e16.PNG)

**Comment by iBobik** [comment] 2016-04-29 10:38
Btw, happens only if preview was switched to mobile view.

**Comment by Pomax** [comment] 2016-04-29 15:48
I suspect this is related to https://github.com/mozilla/thimble.mozilla.org/issues/1474 and might be a duplicate of that issue, just with even worse symptoms due to the smaller screen size

**Comment by humphd** [comment] 2016-05-04 15:38
@iBobik I've got a fix up for review on #1474, so I'll close this.  Thanks for filing and making us aware.  Sorry it broke when we landed the auto-refresh feature.

**Closed by humphd** 2016-05-04 15:38 UTC
