### ISSUE TITLE
Not able to drag and drop files in firefox

### ISSUE THREAD

**Issue by hkirat** [mozilla/thimble.mozilla.org#2409] opened 2017-07-29 16:49 UTC
In firefox version 41.

Dragging and dropping a file fails, file opens in the browser.

![](https://media.giphy.com/media/3oEhmKDr86Y2y8oS4M/source.gif)

**Comment by humphd** [comment] 2017-07-31 19:36
@hkirat what happens in your console?  Also, Firefox version 41 is pretty old, why are you using such an old one?

**Comment by hkirat** [comment] 2017-08-01 04:08
On dragging only, and not dropping the file, I see the following

```js
TypeError: types.forEach is not a function             DragAndDrop 86:13
```

At this point, the types array looks something like this: 
```js
DOMStringList [ "application/x-moz-file", "text/x-moz-url", "text/plain", "Files" ]
```

Not sure why I never updated firefox. Will update and check if it works.

**Comment by gideonthomas** [comment] 2017-08-01 18:46
Looks like this has to do with browser compatibility since DataTransferList isn't supported below Firefox < 50. https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem#Browser_compatibility

My guess is that this won't work on Safari or IE either but I wonder if we should show an error message for this.

**Comment by humphd** [comment] 2017-08-01 19:01
Probably a dupe of https://github.com/mozilla/thimble.mozilla.org/issues/2104, but for older browsers in general.  We should be able to do this, since we have two import strategies that use new and old standards.

**Comment by gideonthomas** [comment] 2017-08-01 19:10
let's close one of these issues and consolidate. Not sure which one you prefer to leave open.

**Closed** 2017-08-01 19:12 UTC
