### ISSUE TITLE
Editor stuck on green [Try Again] screen in Firefox when it can't access localStorage

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2448] opened 2017-08-23 20:18 UTC
Saw this today on a colleagues computer in Firefox. For whatever reason, Firefox wasn't able to access localStorage (as seen in the attached console log capture). Hitting **Try Again** in this instance had no effect or benefit.

![image](https://user-images.githubusercontent.com/25212/29636425-6b732d14-8805-11e7-928b-94e62f6d7b74.png)

We need to detect when this is happening so that we don't keep asking the user to Try Again without a chance of it working.

**Comment by gideonthomas** [comment] 2017-08-25 17:29
@flukeout, just to understand what the issue is, what are the cookie preferences in Firefox for this user? And, to confirm, this wasn't open in Private Browsing mode right?

**Comment by humphd** [comment] 2017-08-28 18:45
Is this the 3rd-party cookie pref again?

**Comment by gideonthomas** [comment] 2017-08-29 17:41
It could be. Depends on what this user has for their cookie settings.

**Comment by humphd** [comment] 2017-11-20 14:20
This was fixed by https://github.com/mozilla/brackets/pull/894.  See http://blog.humphd.org/promise-to-catch/ for more details.

**Closed by humphd** 2017-11-20 14:20 UTC
