### ISSUE TITLE
Create an Account in Chrome broken

### ISSUE THREAD

**Issue by auremoser** [mozilla/thimble.mozilla.org#2119] opened 2017-05-15 19:15 UTC
## Context
Trying to create an account to test thimble before Wednesday release, can't create an account. Have tried multiple user names and passwords in Chrome (Version 57.0.2987.133). Perhaps this is a Chrome issue, perhaps it's a "new account can't be made in staging" issue. Feel free to ignore if that's the case.

## Expected Result
Filled out the account info and click "submit" ---> takes me to login page or somesuch where I can then proceed to login to my account.

## Current Result

Filled out the form to Create an Account, clicked "submit" ---> no effect

Screenshot of the screen I'm seeing, all checks are there, but "submit" button doesn't go anywhere or log the username in the system.

![screen shot 2017-05-15 at 2 53 39 pm](https://cloud.githubusercontent.com/assets/1559703/26074118/a7187700-397e-11e7-871f-8cde5adcaf44.png)

**Comment by humphd** [comment] 2017-05-15 19:16
Thanks for spotting this and filing!  Possible dupe of https://github.com/mozilla/thimble.mozilla.org/issues/2108, cc @flukeout.

**Comment by humphd** [comment] 2017-05-15 19:16
cc @cadecairos

**Comment by auremoser** [comment] 2017-05-15 19:19
sorry, should have checked for dupes!

**Comment by humphd** [comment] 2017-05-15 19:20
@auremoser no, that's on us.  File as many dupes as you like, I'd rather have it recorded.

**Comment by humphd** [comment] 2017-05-18 18:54
Closed with fix in https://github.com/mozilla/id.webmaker.org/pull/437

**Closed by humphd** 2017-05-18 18:54 UTC
Labels: QA
