### ISSUE TITLE
Ability to insert code snippets into files

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1630] opened 2017-01-16 19:48 UTC
For example, when editing HTML, it might be nice to have a dropdown that lets users add...

* A bulleted list with a few blank items
* A small form
* An empty HTML comment
* A definition list
* An empty table...

We could have different snippets depending on the type of file being edited.

**Comment by humphd** [comment] 2017-01-24 19:42
There are extensions for Brackets that do this already, which we can either use, or use as a basis for this, see the following page, and search for "snippets":

https://brackets-registry.aboutweb.com/

Including an extension in Brackets is done via the URL, see https://github.com/mozilla/brackets#optional-extension-loading and https://github.com/mozilla/brackets/blob/master/src/utils/BrambleExtensionLoader.js#L14-L70

**Comment by twigz20** [comment] 2017-01-27 18:02
I'd like to start working on this bug.

**Comment by flukeout** [comment] 2017-01-27 18:19
Thanks @twigz20 let me know if you need any help. I envision some kind of dropdown menu from the  Editor bar....

![image](https://cloud.githubusercontent.com/assets/25212/22382257/bfe420d6-e479-11e6-9c1c-3889f5e23911.png)

One of the tricky bits is that when you click away from the editor, it loses focus, so I'm not sure if it will know where the cursor last was. We'd need to know that because that's where we'd want to insert a snippet.

Let me know how far you get and we can explore the UX around this.

**Comment by Pomax** [comment] 2017-01-28 19:51
This feels like it can tie into the Aframe components menu issue, too.

**Comment by twigz20** [comment] 2017-01-31 15:24
Hey, I was wondering is it possible to point me in the right direction? I'm having difficulty in finding the files I have to work with.
Thanks in advance.

**Comment by gideonthomas** [comment] 2017-02-01 01:13
Hi @twigz20,

There are two parts to this issue tbh, one part needs to be fixed in Thimble, and the other part needs to be fixed in Brackets. Here are some details:

### Brackets code changes
First, make sure you're all setup. Here are the [instructions to setup Brackets](https://github.com/mozilla/thimble.mozilla.org#editor). You will work in that codebase for the following tasks:

1. Add an extension to support adding code snippets
   - Your main code change here is to create an extension (easier than it sounds) for Brackets that will add code snippets
   - First, create a directory in `/src/extensions/default` that will be the name of your extension (follow the convention like the other directories)
   - Create a `package.json` file similar to the one [here](https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble-move-file/package.json) that will be for your "add code snippets" extension
   - Create a `main.js` file that will tell Brackets that we need to add a command for adding code snippets. Your code will be somewhat similar to the contents of [this file](https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble-move-file/main.js)
   - In the same file, the callback that you pass to `CommandManager.register` will be a function you create on your own to add the code snippet
   - The function above should basically get the current position of the cursor for the current editor and insert the code snippet (passed into your function) there. Adapt this piece of code I found in a similar extension (https://github.com/html5andblog/quickjs-brackets-extension/blob/master/main.js#L39-L47) to suit this need
   - FInally, add your extension (whatever you named the folder), to [this list](https://github.com/mozilla/brackets/blob/master/src/utils/BrambleExtensionLoader.js#L18) so that Brackets loads it
2. Add an API (that thimble can use) to use your extension above
   - Your main change here is to implement an API (that uses your Brackets extension) that Thimble can use to add code snippets
   - You will probably make your change [here](https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js#L946). Extend the `BrambleProxy` prototype to have a method called `addCodeSnippet`. Inside, you will probably write a line of code similar to [this line](https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js#L932-L936) with a command `ADD_CODE_SNIPPET` or whatever command you specified/registered with in your extension

To test your extension and API, run Brackets and open `localhost:8000/src/hosted.html`. In the `index.html` file in your browser, place your cursor where you want to add the code snippet. Open your Developer Tools. In it run `bramble.addCodeSnippet("<p>I added this snippet</p>");` and see if it works.

### UI and Thimble code changes
- To add UI to the editor bar as @flukeout suggests, you need to add code to [this HTML file](https://github.com/mozilla/thimble.mozilla.org/blob/master/views/editor/nav-options.html) with CSS [here](https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/stylesheets/editor.less).
- If you add HTML there to enable a dropdown menu, you can then control what it does, for e.g. add snippets, with JS in [this file](https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/editor/js/fc/bramble-menus.js).
- As for what your JS will do, it will probably call something like `bramble.addCodeSnippet(<some code snippet>)`. Note that this function `addCodeSnippet` is actually the Brackets part that will need to be implemented (see above).

You will probably need some design guidance in terms of what the menu should look like and I think @flukeout will be able to provide some info there.


I think it will probably make sense to start with the brackets piece since it's easier (clearer and you you have code to refer to) and does not rely on design input.

Let me know if you have any questions!

**Comment by twigz20** [comment] 2017-02-01 02:16
@gideonthomas Thanks for guiding me in the right direction.

**Comment by twigz20** [comment] 2017-02-07 05:59
Alright, guys, I believe I've completed the bracket code changes.  I'm now able to add code snippets, using my extension, to the editor.

example:

![CodeSnippetsAdder](http://matrix.senecac.on.ca/~jgoguette/media/Code_Snippet_Gif.gif)
I apologize for the low quality gif.

@flukeout I would like some guidance on how you would want me to design the menu.

**Comment by flukeout** [comment] 2017-02-08 01:04
Hey, great stuff @twigz20 - I'll have time tomorrow to provide some guidance. My gut says that we'll want a menu similar to this one...

<img width="200 alt="image" src="https://cloud.githubusercontent.com/assets/25212/22718730/c7c76ffc-ed56-11e6-9e5c-1baa1dc1396a.png">

...but somewhere within the editor bar.

<img width="551" alt="image" src="https://cloud.githubusercontent.com/assets/25212/22718754/ee1dfe8c-ed56-11e6-9757-d4c381f1cbb9.png">

A question

* The ability to see this menu, as well as the options within it, need to depend on the type of file that is being edited. Can you think of a way to do this? We don't want to show HTML snippets when we are editing CSS or JS for example.

**Comment by gideonthomas** [comment] 2017-02-08 01:05
@twigz20 amazing work on this! It's cool to see it working! Would you be able to open up a PR in the brackets repo for your work so far?

**Comment by twigz20** [comment] 2017-02-08 01:33
Thanks! I'll get that PR up soon. 
@gideonthomas I'm not sure how I can get the work I've done in brackets to be seen by the thimble editor. I can't use the function (**bramble.addCodeSnippet()**) that I'm able to use on **localhost:8000** when I attempt to do the same thing on **localhost:3500**.

@flukeout I'll start thinking of ideas on how I'll be able to accomplish that. In addition, I tried working on the [nav-options.html](https://github.com/mozilla/thimble.mozilla.org/blob/master/views/editor/nav-options.html). However, the modifications I made weren't being reflected when I tried testing. example: the source file I see in the debugger does not match the one I made changes to on my machine. But, when I make changes to [bramble-menu.js](https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/editor/js/fc/bramble-menus.js) they are being seen correctly in the debugger. Any idea what might be stopping the changes from being reflected.

**Comment by humphd** [comment] 2017-02-08 02:30
@twigz20 👍

**Comment by flukeout** [comment] 2017-02-08 17:34
@twigz20 I'll check into the issue you're having with ``nav-options.html`` and see if it's the same in my setup.

**Comment by gideonthomas** [comment] 2017-02-09 04:40
@twigz20 since your change touches the bramble client code, you will need to run `npm run build` on brackets (the code that has your `addCodeSnippets` change) first before running `npm start`. That will allow you to use `bramble.addCodeSnippets` in Thimble.

**Comment by gideonthomas** [comment] 2017-02-09 20:05
@twigz20 am I right in assuming that you're also interested in fixing the Thimble side of this?

**Comment by twigz20** [comment] 2017-02-09 21:29
@gideonthomas Yes, i am also interested in fixing the Thimble side of this.

**Comment by gideonthomas** [comment] 2017-02-09 22:40
@flukeout can you provide some direction on this?

**Comment by flukeout** [comment] 2017-02-10 00:38
@twigz20 So, in my dev environment I'm able to see changes when I edit ``nav-options.html`` in ``views/editor`` - maybe it's a chache issue for you? 

As a test, open Chrome dev tools, the hit the triple-dot menu to get to Settings, then find the Network setting and disable the cache...

![image](https://cloud.githubusercontent.com/assets/25212/22809264/d73b8bd6-eee5-11e6-9ed6-f2c957214d67.png)

Now, with dev tools open, try it again and let us know if your changes are showing.

Once you get that running, you can copy the markup for the Gear menu and use the ``    PopupMenu.createWithOffset`` in ``bramble-menus.js`` to turn it into a menu. That's what I did here as a test and here's how it looks...

![snip](https://cloud.githubusercontent.com/assets/25212/22809292/17bc52c6-eee6-11e6-92ba-b474204cd868.gif)

Anyway, let me know if you can get that going and we'll go from there?

**Comment by flukeout** [comment] 2017-02-16 17:54
@twigz20 how's it going? Did my suggestion help?

**Comment by twigz20** [comment] 2017-02-16 21:26
@flukeout Hey, disabling cache was the biggest help!

So far this is what I have.
![ezgif com-f65ea83aee](https://cloud.githubusercontent.com/assets/10361408/23041436/f68e7fa2-f462-11e6-9ab1-ce48ef3df726.gif)

For now those values are hard coded into `nav-options.html` and `bramble-menus.js`.  I've decided to try 2 different approaches to making it more dynamic.

Firstly, creating the `li` tags dynamically and associating them with the information loaded from one of the methods below:
- Loading the various snippets from a `JSON` file. However, I could not figure out how to get the `JSON` file loaded. I've tried using `require("snippets.json")`. But it always appends `.js` to the file. Any idea how I can load in a `JSON` file?

- Creating `javascript objects` in a separate class containing the various snippets and loading. An issue that arose was, all the click events store only the last data in the array. Meaning, for my example gif above all 3 options would only add a table since the table was the last data in the array. I feel I'm close to figuring this part, just needs a little more time.

If you have a different way of handling this, please let me know.

**Comment by flukeout** [comment] 2017-02-17 23:19
Strange error, when did it start happening? @gideonthomas do you know what it might be? Also, do you have some thoughts on where to store the snippets?

@twigz20 Are you able to think of a way to show different snippets depending on what type of file is open?

**Comment by flukeout** [comment] 2017-02-17 23:22
In the meantime I'll do some design work to figure out how to display the menu and how to lay it out. I think a list like you have there now won't be long enough.

**Comment by humphd** [comment] 2017-02-18 01:47
The error he had is caused by having Thimble updated to latest master, but not Brackets.  If you see other people struggling, the fix is to update their Brackets master branch. We did it together in my office today.

**Comment by Pomax** [comment] 2017-02-19 17:08
It sounds like it would be useful for Thimble to know the minimum version of mozilla/brackets needed. Would that be worth doing (if so, we can file a separate issue to tackle that)

**Comment by Pomax** [comment] 2017-02-19 17:09
It sounds like it would be useful for Thimble to know the minimum version of mozilla/brackets needed. Would that be worth doing (if so, we can file a separate issue to tackle that)

**Comment by humphd** [comment] 2017-02-19 17:21
I think that's probably https://github.com/mozilla/brackets/issues/560 with a proper semver strategy.

**Comment by gideonthomas** [comment] 2017-02-20 18:12
@twigz20, for the sake of simplicity (rather than including requirejs plugins and configuring the gruntfile to use them, etc.), I would suggest just having a module with the code snippets for now and requiring them in:
`public/editor/scripts/code-snippets.js`
```js
define(function() {
  return [{
    title: "Add a paragraph",
    snippet: "<p>Add your text here</p>"
  }, {
    title: "Add a table",
    snippet: "<table><tbody><tr><td>RC 1</td><td>RC 2</td></tr></tbody></table>"
  }];
});
```

@gideonthomas to file a follow-up issue to get us away from requirejs and switch to CommonJS/browserify without Grunt (since we only use it to minify and build one file from the requirejs modules).

**Comment by Pomax** [comment] 2017-02-20 18:14
@gideonthomas if you're modernizing, commonjs with babel+webpack is advisable.

**Comment by humphd** [comment] 2017-02-21 01:47
Let's not switch away from `require.js` this term, while the students are using it in Brackets as well, and we aren't going to switch there.

**Comment by gideonthomas** [comment] 2017-02-21 22:08
This definitely will not happen anytime soon, will most likely happen in the summer.

**Comment by humphd** [comment] 2017-02-21 22:43
@raygervais this is the bug where the snippets work is happening, and we'll have to connect you with @twigz20, since your UI could connect with his work.

**Comment by humphd** [comment] 2017-02-21 22:44
Question, why not use the `text` plugin for `requirejs` to include the JSON files?

**Comment by Pomax** [comment] 2017-02-24 00:52
you certainly could, but is there no json plugin?

**Comment by humphd** [comment] 2017-02-24 01:50
There is, see https://github.com/millermedeiros/requirejs-plugins

**Comment by gideonthomas** [comment] 2017-02-27 04:00
@humphd I don't think we include either one of those plugins though. We would need to add them to the Gruntfile as well as the require config in the main.js file as well as a package.json entry. We'd also need to make sure we use the same version that brackets uses so that we're caching and optimizing for size. Seemed like a bit much for this so I thought it might just be easier to make it a module as I mention above.

**Comment by humphd** [comment] 2017-02-27 04:37
@gideonthomas makes sense.

**Comment by twigz20** [comment] 2017-03-07 01:38
So far here is an example of what I've accomplished.
@flukeout I figured out how to show different snippets depending on what type of file is open.
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/10361408/23637925/863aa41c-02ac-11e7-9a8b-184b793d3d7a.gif)

@flukeout any luck in the design for the dropdown?

@gideonthomas @humphd I would like some code review. I feel as though my method of doing this is very inefficient. It has a slight freeze after inserting the snippets when I want to switch to another file. Not sure if i should do a pull request so you guys can offer some assistance.

**Comment by raygervais** [comment] 2017-03-07 02:33
@twigz20, just a lurker atm because it was discussed earlier with @humphd and @flukeout the idea of integrating your snippets work into the space under the file tree. 

Though the idea was shelved at the moment, instead serving a possible place for a console that is still being discussed, I wanted to say that seeing your snippets implementation so far is absolutely brilliant!

**Comment by twigz20** [comment] 2017-03-07 16:15
Thanks! @raygervais we should definitely talk about this and get me up to speed with what was discussed.

**Closed** 2017-05-04 20:09 UTC
Labels: Assigned to Contributor, Good First Bug
