### ISSUE TITLE
Hitting "command" key while editing de-indents current line.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1575] opened 2016-11-03 17:11 UTC
**Steps to reproduce**

* On a mac, in Chrome, hit tab while editing a line
* The line you are one becomes de-indented one tab to the left

![thimble-command-tab](https://cloud.githubusercontent.com/assets/25212/19976638/cade96f6-a1ad-11e6-8709-207f0d4eae79.gif)

**Comment by gideonthomas** [comment] 2016-11-03 18:28
Dupe of https://github.com/mozilla/thimble.mozilla.org/issues/1572

**Closed by gideonthomas** 2016-11-03 18:28 UTC
Labels: bug
