### ISSUE TITLE
Update the mozilla logo on the main page

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1744] opened 2017-02-16 17:11 UTC
Do we need to update the mozilla logo in the main page footer to use the new branding, or is the old wordmark still valid branding? @flukeout any ideas?

**Comment by hannahkane** [comment] 2017-02-16 17:13
cc @xmatthewx

**Comment by flukeout** [comment] 2017-02-16 17:14
Dupe of #1664 - I'll update the logo in header & footer.

**Closed by flukeout** 2017-02-16 17:14 UTC
