### ISSUE TITLE
remastering code with require.js fails to work, no clear errors in console, while still working in plnkr 

### ISSUE THREAD

**Issue by voltel** [mozilla/thimble.mozilla.org#1709] opened 2017-02-08 07:28 UTC
The arrangement of js files works fine at http://plnkr.co/edit/chaGUYSc2eXJDnIIG8bK with no funny messages in console. But within https://thimble.mozilla.org/ru/user/lugi/770581 it generates two vague errors in console and it doesn't work at all (won't even start execution of main.js):
1) [Brackets LiveDev] No subscribers for message XMLHttpRequest
2) Error: ./config.json HTTP status: 404 -   text.js:1:4596
text.get/xhr.onreadystatechange 
handleError  
setResponse  
XMLHttpRequestLiveDev/self.send/<  
        
This is my son's school schedule project, so I'd appreciate a quick help. Thanks!

**Comment by humphd** [comment] 2017-02-08 15:03
@voltel please let your son know that we're sorry you're hitting this issue.  I'm looking at it now, and I strongly suspect that the issue is related to 2 things, neither of them your fault:

* The way Thimble currently works, loading static content in the live preview works using Blob URLs vs network requests. Therefore, anything that needs to get dynamically loaded (e.g., requirejs loading scripts or any JS that dynamically generates URLs) will break.  We have a bug to fix this using Service Workers, but it won't be ready for a while.  For reference, this is https://github.com/mozilla/brackets/issues/549
* We shim XMLHttpRequest in the live preview to deal with not having a real server, and try to serve requests with Blob URLs from the editor's filesystem.  It's not perfect, and I suspect that you're hitting a bug in our implementation, when requirejs' text plugin tries to XHR get the file.  We can likely fix that in addition.

I wish I had a better solution for you here, other than to make excuses and tell you about our limitations and bugs.  Making Thimble work well for dynamic JS projects like the one your son is building is something we want to do.

**Comment by voltel** [comment] 2017-02-08 15:16
Thank you for a reply.
I recommended our school's teacher of CS to use Thimble in class. It's
child-friendly, but has enough power under the hood for projects that are a
bit more complicated than post-cards.

Unfortunately, I encountered another issue with URL, since I accidentally
revoked the published project and lost previous URL, which is quite a
misfortune since a lot of people have already been shared the old one. I
wrote an email about this with more detail earlier today.

Could you, please, help me regain old URL for a published project?



Best regards,

*Volodymyr Telnov*
*Ukraine*
*+38-067-67-99-131*

2017-02-08 17:03 GMT+02:00 David Humphrey <notifications@github.com>:

**Comment by humphd** [comment] 2017-02-08 15:19
@cadecairos, @gideonthomas are you able to help @voltel recover the project URL?

Also, thanks for encouraging the school to use Thimble.  It's too bad that we've not been able to support the exact use case you needed for your son.  It's great that you're helping to spread Thimble as a tool for kids to learn programming.

**Comment by gideonthomas** [comment] 2017-02-08 20:42
Copying text from the email so as to continue the conversation here:

> One thing I might be able to do is to copy the contents of the project and put it under the https://thimbleprojects.org/lugi/197094/ url. However, please note that you will not be able to update the contents of that project on that link after I enable it. Any changes you make to the project will only be reflected in the new URL: https://thimbleprojects.org/lugi/202703. Effectively, the old url will be locked to a certain version of your project.

**Comment by gideonthomas** [comment] 2017-02-08 20:54
This has been resolved with the above solution, closing.

**Closed by gideonthomas** 2017-02-08 20:54 UTC
Labels: support
