### ISSUE TITLE
Facebook blocks sharing of "thimbleprojects.org" links.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2289] opened 2017-06-13 14:29 UTC
Yep, it does. Deemed "unsafe" or something like that. I used the contact form that shows up when you try to post a blocked link, so maybe there's a chance we'll get an explanation etc. Doesn't seem likely.

Any other ideas for figuring this out?

* Get mozilla twitter to ask the facebook twitter about it?
* Do we know anyone who has any contacts at FB?
* ...?

Walled gardens, yey!

**Comment by humphd** [comment] 2017-06-13 14:45
Dupe of https://github.com/mozilla/thimble.mozilla.org/issues/1898

**Closed by humphd** 2017-06-13 14:45 UTC
