### ISSUE TITLE
cool features is sensory overload

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#2133] opened 2017-05-16 00:21 UTC
with all the images playing, this is sensory overload town. It might be better to put a big play button over each image and not playing until the user clicks/touches?

**Comment by humphd** [comment] 2017-05-16 15:07
Closing as dupe of https://github.com/mozilla/thimble.mozilla.org/issues/2084

**Closed by humphd** 2017-05-16 15:07 UTC
Labels: QA
