### ISSUE TITLE
Thimble and WebVR: fix remix overlay issue with WebVR toggle

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1608] opened 2017-01-12 19:07 UTC
We have a bug in published projects, in both orientations on mobile, where the Remix button blocks the VR button

![](https://i.imgur.com/1xrHqpP.png)

**Comment by gideonthomas** [comment] 2017-01-13 19:28
Possible solutions from previous discussions: https://github.com/mozilla/thimble.mozilla.org/issues/1515

**Comment by humphd** [comment] 2017-01-24 19:24
NOTE: the code that actually injects this remix button, and places is it is in https://github.com/mozilla/thimble.mozilla.org/blob/master/public/resources/remix/index.js and https://github.com/mozilla/thimble.mozilla.org/blob/master/public/resources/remix/style.less

**Comment by ZenanZha** [comment] 2017-02-09 23:09
I got where the problem is! I thing I think I could fix it right away. Thank god.

**Comment by ZenanZha** [comment] 2017-02-09 23:27
I think we could just move the remix button a little bit up(from bottom: 6px to 26px), so both button could works at the same time.
In this way, the remix button will be more friendly for a longer smart phone(like, iphone 7) user to press.

**Comment by gideonthomas** [comment] 2017-02-11 00:48
@flukeout what do you think of this solution?

**Comment by flukeout** [comment] 2017-02-17 00:00
Work has moved to #1724

**Comment by Rajat-dhyani** [comment] 2017-03-01 13:31
i followed  [#1724](https://github.com/mozilla/thimble.mozilla.org/pull/1724) but i guess @ZenanZha  is not really following up... Can i take over the work if no body is working on it ?

**Comment by ZenanZha** [comment] 2017-03-01 14:14
@Rajat-dhyani  Sorry, man. I just spent some time on study CSS on my own. I'm about to  finish my work before Friday.

**Comment by Rajat-dhyani** [comment] 2017-03-01 15:18
okay no problem.. @ZenanZha i will find some other issue to work upon.... thanx for replying anyway 👍

**Comment by flukeout** [comment] 2017-03-13 23:52
Closed via work in #1724 - thanks again @ZenanZha

**Closed by flukeout** 2017-03-13 23:52 UTC
Labels: good first bug
