### ISSUE TITLE
Image preview in Editor visible overtop of full-screen preview.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1681] opened 2017-01-30 19:20 UTC
This is happening in Chrome, see below...

![preview](https://cloud.githubusercontent.com/assets/25212/22437699/eb477514-e6dd-11e6-8a66-7c0d728792bc.gif)

Probably related to #1518

This can probably be resolved by adjusting the z-index of the fullscreen preview to make sure it overlaps everything in the editor.

**Comment by humphd** [comment] 2017-01-30 19:36
This is probably fixed with a `z-index` change to our fullscreen preview to layer it on top of all content in the editor.  See discussion in #1518

**Comment by Mordax** [comment] 2017-02-07 15:04
I'd like to try fixing this.

**Comment by humphd** [comment] 2017-02-07 20:51
@Mordax, sounds good, it's yours.  You might also want to tackle #1518 at the same time, since they can probably both be fixed with the same thing.

**Comment by flukeout** [comment] 2017-02-08 18:05
In addition to what is mentioned in #1518, there is also one more symptom of the z-index problems: You can change the width of the file tray (and probably editor too) by dragging _through_ the full screen preview, here's what that looks like...

![resize](https://cloud.githubusercontent.com/assets/25212/22750550/21111fb0-ede6-11e6-8fc5-044004e87d03.gif)

**Comment by humphd** [comment] 2017-02-08 18:33
So many fun ways to break our code!

**Comment by Rajat-dhyani** [comment] 2017-03-14 19:25
hey @Mordax if you are not working on this issue can i take this over ? 
c.c : @flukeout @humphd

**Comment by Mordax** [comment] 2017-03-15 18:17
@Rajat-dhyani Sorry, still working on it.

**Comment by Rajat-dhyani** [comment] 2017-03-15 19:10
@Mordax okay no problem. thanks for replying 👍

**Comment by humphd** [comment] 2017-03-23 18:48
@Mordax are you indeed still doing this?  It's been inactive a long time.

**Comment by MargarytaChepiga** [comment] 2017-04-07 16:59
@humphd, If @Mordax is not interesting anymore, I would love to work on this bug.

**Comment by humphd** [comment] 2017-04-08 18:48
@MargarytaChepiga OK, go for it.

**Comment by MargarytaChepiga** [comment] 2017-04-21 02:20
Hello, @humphd @flukeout 

I have tried to reproduce the bug. On thimble I was able to get the bug:
![test2](https://cloud.githubusercontent.com/assets/15698572/25259050/96cdb002-2611-11e7-87eb-db3f9759f162.gif)
![test4](https://cloud.githubusercontent.com/assets/15698572/25259062/a90bc2a4-2611-11e7-98bd-7167365db2dd.gif)

However on the localhost, I can't reproduce it. 
![test3](https://cloud.githubusercontent.com/assets/15698572/25259079/c13dc73c-2611-11e7-8773-df2d0f68280f.gif)
![test1](https://cloud.githubusercontent.com/assets/15698572/25259089/d5f10216-2611-11e7-9ded-b2a9483686f6.gif)

However, I can still detect the editor's border when I hover over with the mouse as follows:
![test5](https://cloud.githubusercontent.com/assets/15698572/25259466/38024238-2614-11e7-9433-9b46f6e1e986.gif)

Could you please tell me if you were able to reproduce the black blob on localhost? 
Any advice to reproduce the black blob would be appreciated. Otherwise, please confirm that I should fix the z-index for the fullscreen preview.

**Comment by MargarytaChepiga** [comment] 2017-04-21 04:03
Hello @humphd @flukeout,

I have set the z-index for horz-resizer to -1 and it has disappeared in fullscreen preview mode. However the issue I ran into is that horz-resizer disappears totally when disabling fullscreen preview. 

![z-index](https://cloud.githubusercontent.com/assets/15698572/25262415/e64a9fbe-2625-11e7-9345-f90d18894532.gif)


I believe we need to set the z-index to -1 only when switching to fullscreen preview mode and switch it back to the default value when switching out of fullscreen preview mode. Now I know this could be the solution in theory but I'm not sure where to start. 

Please confirm and correct me if I'm wrong. Thanks.

**Comment by flukeout** [comment] 2017-04-21 18:20
Hi @MargarytaChepiga thanks for looking into this! I think you're on the right track. One of the things that can help, is that if we enter fullscreen mode, there's a div in our page called 
``<div id='main=view'>`` that gets a class called ``fullscreen-preview``. This div wraps all of the editor and that is how we can set the different fullscreen styles.

Knowing this, we can write a style that affects the resizer element ``z-index`` property. I'd recommend looking in the project to see where the ``fullscreen-preview`` styles are set and then adding a new style for the resizer bar in there. You can check to see what classes to apply the styles to if you inspect the Dom with you dev tools and find the resizer elements.

**Comment by MargarytaChepiga** [comment] 2017-04-22 04:20
Hello @flukeout @humphd, 

So I was able to achieve this:  
![fix](https://cloud.githubusercontent.com/assets/15698572/25301100/cb09b51a-26ec-11e7-941b-6d73cda6ab8b.gif)

The arrow is still visible as you can see. However, it doesn't resize anything (as in the fullsceen mode does not affect the side bars outside the fullscreen mode) which is nice. Also, the change does not affect the ability to resize in the normal mode ( like I mentioned in the comment above). 
![fix2](https://cloud.githubusercontent.com/assets/15698572/25301173/a9e8494a-26ed-11e7-98de-f18738d87080.gif)

Please let me know if this looks good so I can go ahead and commit the changes. Any suggestions would be appreciated.

**Comment by flukeout** [comment] 2017-04-22 18:22
Thank you for the update @MargarytaChepiga - I think the best thing to do at this point would be to make a Pull Request with your latest changes. That way we can see the code and try out the changes. The Pull Request doesn't have to be "the final version" - it can be a work in progress that we can improve if we have to.

Thanks!

**Comment by MargarytaChepiga** [comment] 2017-04-23 00:20
Thank you @flukeout ! I was actually able to remove the arrow today! Surprisingly it all wasn't about the z-index, but about the visibility of the property. Anyway, here is the pull request: https://github.com/mozilla/brackets/pull/745

I wasn't sure where should I push it, but since I was making changes inside the brackets I opened the pull request there.

**Closed** 2017-06-07 17:53 UTC
Labels: Assigned to Contributor, bug, Good First Bug
