### ISSUE TITLE
Let users turn off auto-complete

### ISSUE THREAD

**Issue by chadsansing** [mozilla/thimble.mozilla.org#1761] opened 2017-02-20 18:23 UTC
Discourse user [zachw asks how we might disable autocomplete inside Thimble](https://forum.learning.mozilla.org/t/overrides-for-editor/1473).

How might we do this by project or account?

**Comment by humphd** [comment] 2017-02-20 18:26
https://github.com/mozilla/brackets/pull/601 is adding support for turning off autoclosing tags.  I wonder if there are other aspects of what we "auto-complete" that need this?

**Comment by humphd** [comment] 2017-03-28 19:00
From #1919, @flukeout suggests we make it possible to turn off all the code hints too.

**Comment by Pomax** [comment] 2017-03-28 19:28
As long as it's in two steps that would be nice. Perhaps the dev tools behaviour is useful here, too: autocomplete shows you your options, but does not kick in unless you hit the right cursor key. Hitting space or enter just does literally that, adding a space or a newline (in multiline mode)

**Comment by flukeout** [comment] 2017-03-28 21:25
Just for clarity, I'm going to close this issue as I'm pretty sure from reading the Discourse post that this is about auto closing tags - so it's a dupe of #1262 - which is already being worked on.

**Closed by flukeout** 2017-03-28 21:25 UTC

**Comment by flukeout** [comment] 2017-03-28 21:30
Filed updated issue in https://github.com/mozilla/thimble.mozilla.org/issues/1920
