### ISSUE TITLE
Cannot Publish 

### ISSUE THREAD

**Issue by mrsgoehring** [mozilla/thimble.mozilla.org#1458] opened 2016-03-23 13:06 UTC
I cannot publish my Thimble site.  Up in the left hand corner by my project name it says "Saving Failed Retrying" and it never stops saying this. 

I have to publish this for a class that I'm taking.  

![capture](https://cloud.githubusercontent.com/assets/18030755/13986022/0f91315a-f0ce-11e5-804b-6f7a0e4f60e0.PNG)

**Comment by gideonthomas** [comment] 2016-03-23 17:15
Hi @mrsgoehring, did you happen to rename a folder in your project? If so, unfortunately, that might have caused the issue. We are working on a fix for that based on the issue filed here: https://github.com/mozilla/thimble.mozilla.org/issues/1311 but realistically, it might not be fixed in time since the fix is a bit of a challenge to implement . 

We are sorry that you are experiencing this issue, especially since your classwork depends on it. There are mainly two options here that work as a quick fix (regardless of what caused the issue):
* **Option 1:** Exporting the project and re-importing it again. This is a bit complex but has good results. To do so:
 1. Click on your name on the top-right corner near the Publish button and select "Export (.zip)" from the menu. This will download your project to your computer.
 2. On your computer, go to the folder where the zip file was downloaded and extract the zip file. You should now have a `projects` folder. Go into the `projects` folder where you should be able to see your project files.
 3. In Thimble, create a new project. Unfortunately, you might have to manually change the name and description of your new project to whatever you had in your old project.
 4. On your computer, select all the files in the `projects` folder (all at once or you can do this individually) and drag them into Thimble. There is a caveat though. If you have a folder in your `projects` folder, you can't drag and drop it into Thimble. Instead, you will have to manually create the folder in Thimble, drag and drop the files in that folder from your computer into Thimble and then right click each of those files on Thimble and "Move To" the newly created folder on Thimble.
 5. You should now basically have a copy of your project and should be able to publish without an issue.
* **Option 2:** Exporting the project, sending it to us and remixing our published version of that project.
 1. Follow step 1 from Option 1.
 2. Send us (let us know your preferred way to do this) the zip file and we will create a project for you.
 3. Remix that project (we will give you the link) and change the title and description as needed and you should be able to publish. We will take down our version of the project once you remix it.

Once again we apologize for the inconvenience that this is causing you. We're working on fixing this issue asap. Let us know what you plan to do!

**Comment by mrsgoehring** [comment] 2016-03-23 20:20
Thank you so much for the quick response! I'll try this.

**Comment by mrsgoehring** [comment] 2016-03-23 20:42
I just went through option 1 and although everything copied and is correct in the preview. I'm still having the same issue where it will not publish and says "saving failed, retrying..."

How should I sent the project to you to remix?

**Comment by gideonthomas** [comment] 2016-03-23 20:52
Hmm that's weird. You can send the zipped file to gideon@mozillafoundation.org and I can post the remixable link in this bug.

If I am not able to reproduce this error on my end, would you be able to select/copy/paste all the content you see in the console (which you can open up on [Firefox](https://developer.mozilla.org/en/docs/Tools/Browser_Console#Opening_the_Browser_Console) and [Chrome](https://developer.chrome.com/devtools/docs/console#basic-operation)) into this bug? That will give us some information which will help us debug.

**Comment by mrsgoehring** [comment] 2016-03-23 21:12
You bet. I'm sending now. It will come from my school account cgoehring@epsne.org.

**Comment by gideonthomas** [comment] 2016-03-23 21:34
@mrsgoehring Thanks! Looks like you've uncovered a pretty nasty bug haha. I'm working on investigating this and fixing it right now and will have it up by today/tomorrow morning latest. Do you have a deadline on this project? If it is before the timeframe I mentioned, let me know when it is and I will do my best to make sure it is fixed long before then.

**Comment by mrsgoehring** [comment] 2016-03-23 21:42
No worries! It's not due until this Monday the 28th.  Thanks, Gideon :)

**Comment by gideonthomas** [comment] 2016-03-24 15:42
You're very welcome! @mrsgoehring I'm still trying to figure out what went wrong but I was not able to reproduce the error when I tried again. The good news is that now I have a project that you can remix and continue working on: [https://thimbleprojects.org/gideonthomas/46972](https://thimbleprojects.org/gideonthomas/46972). Let me know if you have any more issues and let me know when I should take down my published project!

**Comment by mrsgoehring** [comment] 2016-03-24 16:13
You are my hero! I pulled it down but I'm on the middle of teaching a math class...can you leave it until the end of the day? 

Thank you!!!!

**Comment by mrsgoehring** [comment] 2016-03-24 20:16
Ok, I've got it up and running. You can take it down. Thanks again for your help.

**Closed** 2016-03-25 00:10 UTC

**Comment by mrsgoehring** [comment] 2016-03-27 19:22
Gideon,

The error happened again. I created a new folder and named it then realized I had misspelled so I went back to rename it and started getting the error message.  There were no files in the folder yet.

I was able to recreate my page this time by exporting and uploading my files into a new project so no worries. I just thought it might be helpful for you to know what I was doing when the error occurred. 

Thanks,
Crista

**Comment by gideonthomas** [comment] 2016-03-28 16:25
Ah I'm sorry to hear that! I know it is a bit of a pain to export and re-import your project into Thimble. We are aware of a bug with renaming folders and are figuring out a solution here: #1311 and hopefully that will fix your problem.

Thanks for letting us know!
