### ISSUE TITLE
ngRoute = 100% RAM and freeze in thimble

### ISSUE THREAD

**Issue by Mlocik97-issues** [mozilla/thimble.mozilla.org#2609] opened 2018-02-05 16:36 UTC
Write this code:

https://www.w3schools.com/angular/angular_routing.asp

Thimble will freeze and after few minutes browser is using a lot of ram (8GB +)

**Comment by gideonthomas** [comment] 2018-02-05 16:59
@Mlocik97-issues, which browser are you using?

**Comment by Mlocik97-issues** [comment] 2018-02-05 17:11
Chrome 63 & 64

**Comment by Mlocik97-issues** [comment] 2018-02-05 17:15
It happend also in firefox 55

**Comment by gideonthomas** [comment] 2018-02-07 21:35
hmm, which example from that page are you using? I can't seem to reproduce this issue. Do you have any extensions installed that might do this (for e.g. anything javascript related)

**Comment by humphd** [comment] 2018-03-06 16:06
Closing due to lack of info.  If this problem happens again, please re-file.

**Closed by humphd** 2018-03-06 16:06 UTC
Labels: support
