### ISSUE TITLE
Feature request > Allow toggle of Editor options by clicking the option label

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2116] opened 2017-05-15 19:02 UTC
In this menu here...

![image](https://cloud.githubusercontent.com/assets/25212/26074345/50d0afd8-3966-11e7-9b68-63ccb11f36e7.png)

Would be nice to be able to click the label the change the setting instead of having to click the toggle itself. When hovering on the label, we should highlight the toggle somehow to show that it will be toggled if you click.

**Comment by feihaozi77** [comment] 2017-09-28 17:29
Can I work this one? if no one is being assigned?

**Comment by humphd** [comment] 2017-09-28 17:33
@feihaozi77 it's all yours.

**Comment by flukeout** [comment] 2017-09-28 17:33
Sounds good @feihaozi77 - all yours. Let me know if you have questions. This will require you running both Thimble and Brackets locally.

**Comment by feihaozi77** [comment] 2017-09-28 17:34
can you provide a brief STR ?

**Comment by flukeout** [comment] 2017-09-28 17:37
Sure thing, check out this gif...

![toggle-click](https://user-images.githubusercontent.com/25212/30981343-ac956ad6-a449-11e7-961a-a62073a72611.gif)

Notice how only clicking the actual toggle changes the setting? When I click the label nothing happens, but it should! Clicking the label should have the same behavior as clicking the toggle UI.

**Comment by feihaozi77** [comment] 2017-09-28 19:24
@flukeout i was following the automated installation section in the readme file to set up the environment, but there are still some confusions in my mind, since you told me both thimble and brackets should be running locally, could you explain what is the relationship between those two tools? (I know brackets is a editor while thimble is like a online web based editor)

**Comment by flukeout** [comment] 2017-09-28 19:31
Take a look below...

<img width="948" alt="image" src="https://user-images.githubusercontent.com/25212/30986574-81aa1ee2-a459-11e7-9b97-87d7e6d46266.png">

In essence, everything above the red line is "Thimble" and everything below is "Brackets". The homepage also lives in the Thimble repo. Let me know if that helps. Thimble is like the wrapper piece that adds the UI for all of the editor settings, account management as well as the ability to publish etc.

**Comment by feihaozi77** [comment] 2017-09-29 00:57
@flukeout when i modify the main.js in dist/editor/scripts and restart the server, the main.js always restore back to the previous state which is without my modification. Do you know what is the cause of this?

**Comment by humphd** [comment] 2017-09-29 01:19
cc @gideonthomas, who can explain the webpack build stuff to you, and where things live in the src.

**Comment by feihaozi77** [comment] 2017-09-29 01:25
@gideonthomas when i modify the main.js in dist/editor/scripts and restart the server, the main.js always restore back to the previous state which is without my modification. In other word, right now i'm not be able to change code in dist folder.  My guess is that something happened during the build when i restart the thimble server. Do you know what is the cause of this?

**Comment by feihaozi77** [comment] 2017-09-29 03:02
@flukeout @humphd when I was making changes to the menu.js file under public/editor/scripts/ui the changes in the menu.js file did not get compiled into the dist folder.  I tried restart the server the change still does not take any effect. but when i making changes into the html codes in the view folder the server is picking up the changes immediately.

**Comment by gideonthomas** [comment] 2017-09-29 16:16
@feihaozi77 you should never need to touch the `dist/` folder for anything. All your changes need to be made in the `public` folder.
Re: your second comment, when you make a change to menu.js and save, do you see any logs in your console? Also, how are you restarting the server?

**Comment by feihaozi77** [comment] 2017-09-29 18:25
@gideonthomas Thank you for the response! the problem for me is that I did not disable cache in my browser, after i clear all the cache i'm able to see the changes now

**Comment by feihaozi77** [comment] 2017-09-29 18:35
@flukeout just want to clarify the issue, when user hover the label text, do you want the toggle button to be highlighted or the label text to be highlighted?

**Comment by humphd** [comment] 2017-09-29 19:24
@feihaozi77 you don't need to highlight anything, just make the entire rectangle clickable vs. just the toggle.

**Comment by feihaozi77** [comment] 2017-09-29 19:28
@humphd I already made the label text clickable to toggle the button, just want to make sure that's what @flukeout want or the entire rectangle

**Comment by feihaozi77** [comment] 2017-09-29 20:13
![texttoggle](https://user-images.githubusercontent.com/13205171/31034197-03e32dd6-a531-11e7-94cd-d239191d7feb.gif)
this is what i've done so far let me know what you think about it @flukeout  @humphd

**Comment by humphd** [comment] 2017-09-29 20:42
@feihaozi77 looking very nice!  One thing you can do is also change the cursor pointer to a hand vs. an arrow, so people know they can click (the toggle already does this, the label just needs it).  Go ahead and open a pull request for this, and we can discuss this more there.

**Comment by feihaozi77** [comment] 2017-09-29 20:44
@humphd I'll add the hand-cursor thing first, once i done that i'll open the PR

**Comment by flukeout** [comment] 2017-10-02 17:39
Looks great @feihaozi77 - looking forward to the PR.

**Comment by humphd** [comment] 2017-10-05 18:22
Merged.

**Comment by humphd** [comment] 2017-10-05 18:23
@feihaozi77 for next time, a tip: make your GitHub PR description include `"Fix #2116:...` and GitHub will autoclose issues when PRs land.

**Closed by humphd** 2017-10-05 18:22 UTC
Labels: Assigned to Contributor, Feature Request, Good First Bug
