### ISSUE TITLE
Improve the design and contrast of Thimble's code window for presenations

### ISSUE THREAD

**Issue by chadsansing** [mozilla/thimble.mozilla.org#1533] opened 2016-08-07 17:41 UTC
Users can't read the Thimble FILES menu or code window in well-lit rooms because the display themes are too low-contrast. We should develop a presentation theme or improve current themes for readability during presentations, thinking past traditional fonts and colors used by coders.

cc @anmechung @hannahkane

**Comment by gideonthomas** [comment] 2016-08-08 04:07
cc @flukeout

**Comment by humphd** [comment] 2017-05-12 00:24
Dupe of #1251.

**Closed by humphd** 2017-05-12 00:24 UTC
Labels: delightful!, UI
