### ISSUE TITLE
tooltip for the settings menu only works for the switch

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#2152] opened 2017-05-16 21:19 UTC
mouse-over for a settings switch tells you what it does - someone reported they expected a tooltip while mouse-over'ing the text label instead, and when that didn't tell them what the setting did, got confused.

![screenshot 52](https://cloud.githubusercontent.com/assets/177243/26128806/8b4e3914-3a42-11e7-95c7-3191fe108327.png)

**Comment by flukeout** [comment] 2017-05-17 16:55
This pairs nicely with https://github.com/mozilla/thimble.mozilla.org/issues/2116 which is about making the Label also and not just the toggle. Also that label needs changing, I thought we had a PR for that already.

**Comment by humphd** [comment] 2017-10-06 14:56
Assigning this to @scarecrow21.  This is similar to what was recently done in https://github.com/mozilla/thimble.mozilla.org/commit/00a85b9ff8c5669276c607ec6b38252d4e47c970, and you can use that as a guide to figure out where to add these tooltips.  Basically, we'll want to move them off of the toggles, and onto the `<li>` elements.  Let me know if you have questions, and feel free to come and chat with us on https://chat.mozillafoundation.org/mozilla/channels/thimble

**Comment by scarecrow21** [comment] 2017-10-07 11:07
Hi. I'm new to open source.To set up my dev environment,  I'm following this [blog/guide](http://blog.humphd.org/fixing-a-bug-in-mozilla-thimble/.) I get the following error when I do vagrant up: 
![screenshot from 2017-10-07 16-24-35](https://user-images.githubusercontent.com/24637176/31307251-a666ef2e-ab4f-11e7-8e56-f0791c8b58ce.png)
How to resolve it?

**Comment by scarecrow21** [comment] 2017-10-07 18:42
This came up after I did vagrant plugin repair followed by vagrant up.
![screenshot from 2017-10-07 23-58-16](https://user-images.githubusercontent.com/24637176/31310859-36ebf2da-ab8f-11e7-976a-6fa9d6e7e3a8.png)

**Comment by humphd** [comment] 2017-10-07 18:44
It looks like it hasn't actually downloaded the box yet.  Can you try doing:

```
vagrant destroy
vagrant up
```

**Comment by scarecrow21** [comment] 2017-10-08 06:36
I reinstalled vagrant. This time it didn't show any errors like before when I did vagrant up. When I went to 'localhost:3500' in the browser, the page didn't load. Here is a part of the output that came on the command line when I did `vagrant up`:
![screenshot from 2017-10-08 11-57-39](https://user-images.githubusercontent.com/24637176/31314557-f1b7a6be-abf2-11e7-994f-f9d5733ef43e.png)

This is the output of `VAGRANT_LOG=info vagrant` up: 
![screenshot from 2017-10-08 12-04-24](https://user-images.githubusercontent.com/24637176/31314561-0a0da538-abf3-11e7-8124-77d582bdc87d.png)

**Comment by scarecrow21** [comment] 2017-10-08 08:47
I reinstalled Vagrant (uninstalled using: `rm -rf /opt/vagrant` `rm -f /usr/bin/vagran` and installed using: `sudo dpkg -i vagrant_2.0.0_x86_64.deb`) . I re-cloned the thimble repo locally. I ran `npm install` `
[vagrant_up_log.txt](https://github.com/mozilla/thimble.mozilla.org/files/1366741/vagrant_up_log.txt)
npm run env` and `vagrant up` in the thimble directory. The output of `vagrant up` is in the picture. The output to `VAGRANT_LOG=info vagrant up` is attached as a .txt file.
![screenshot from 2017-10-08 14-02-27](https://user-images.githubusercontent.com/24637176/31315228-62fc630e-ac03-11e7-973b-6f361cdf5897.png)

**Comment by scarecrow21** [comment] 2017-10-08 12:53
I reinstalled vagrant and re-cloned the thimble repo. then I did vagrant up, this is the error i got:

![screenshot from 2017-10-08 18-16-38](https://user-images.githubusercontent.com/24637176/31316952-9acf506a-ac27-11e7-82b6-7cc88acfb6ee.png)

**Comment by scarecrow21** [comment] 2017-10-08 13:56
The problem is solve. I ran the following commands `sudo apt-get update && sudo apt-get remove --purge virtualbox-5.0 && sudo apt autoremove` to remove anything left from the old installation. `sudo /sbin/vboxconfig`  to rebuild the Kernel modules for Virtual box. I then restarted my pc and it works like a charm now.

**Closed** 2017-12-03 21:23 UTC
Labels: Assigned to Contributor, Good First Bug, Hacktoberfest
