### ISSUE TITLE
[IE11] Missing Math.log10 breaks Brackets

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2524] opened 2017-10-09 19:39 UTC
Is anyone able to test thimble on IE11? Have an educator who is stuck using it and the editor won't load. Curious maybe if it's something easy to diagnose / fix.

**Comment by daubaris** [comment] 2017-10-10 17:15
I can check it out.

**Comment by marcobeltempo** [comment] 2017-10-10 17:16
Here's the [console log](https://gist.github.com/marcobeltempo/90b55cc5aa58d56181de64d3c2a9eb4b) from thimble.mozilla.org in IE11. Hopefully it's useful for someone.

**Comment by gideonthomas** [comment] 2017-10-10 17:24
@flukeout what OS is it? We have a few IE11 related issues that only happen in certain OS' like this one: https://github.com/mozilla/brackets/issues/598

**Comment by daubaris** [comment] 2017-10-10 17:25
I get the same response on Windows 10 IE11.

**Comment by daubaris** [comment] 2017-10-10 17:30
Well the Math.log10 seems not to be supported by IE - ![mozilla docs](https://imgur.com/a/SQBeO). And console seems to complain about that `TypeError: Object doesn't support property or method 'log10'`.

**Comment by humphd** [comment] 2017-10-10 17:43
@daubaris nice find.  The problem is [here in Brackets](https://github.com/mozilla/brackets/blob/master/src/filesystem/impls/filer/lib/Sizes.js#L48):

```
src/filesystem/impls/filer/lib/Sizes.js:48:        var exponent = Math.min(Math.floor(Math.log10(num) / 3), UNITS.length - 1);
```

The easiest fix here is to add [this polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log10#Polyfill) to the Brackets [Compatibility.js file](https://github.com/mozilla/brackets/blob/master/src/utils/Compatibility.js):

```js
Math.log10 = Math.log10 || function(x) {
  return Math.log(x) * Math.LOG10E;
};
```

@daubaris do you want to do this?  cc @Pomax

**Comment by daubaris** [comment] 2017-10-10 17:44
@humphd Sure!

**Comment by Pomax** [comment] 2017-10-10 17:48
I don't currently have IE11, only Edge (windows 10 pro x64) but I can set up a win7 VM with IE11 to do some testing if necessary.

**Comment by humphd** [comment] 2017-10-10 20:21
Fixed by @daubaris in https://github.com/mozilla/brackets/pull/883.

**Closed by humphd** 2017-10-10 20:21 UTC
Labels: brackets, Good First Bug
