### ISSUE TITLE
Allow project export to .zip file when not logged in

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#981] opened 2015-08-30 20:06 UTC
We have the `Export project...` menu item hiding in the authenticated drop-down menu.  We should allow you to get a .zip file of your project without having to be logged in.

**Comment by humphd** [comment] 2017-01-24 18:15
Fixing this requires us to move the menu option for export out of the logged in user menu (or add a second menu option).  Right now it looks like this:

<img width="451" alt="screen shot 2017-01-24 at 1 12 22 pm" src="https://cloud.githubusercontent.com/assets/427398/22260316/d52f74da-e236-11e6-9be9-83cac4e58a75.png">

Should we put a new button beside the '+' in the file tree that means "Download"? @flukeout, can you weigh in?

The code in Bramble that does the zip stuff is here https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/RemoteCommandHandler.js#L146-L148 (see `ArchiveUtils` https://github.com/mozilla/brackets/blob/master/src/filesystem/impls/filer/ArchiveUtils.js).

In Thimble you trigger it like this:

https://github.com/mozilla/thimble.mozilla.org/blob/fa3dde088dc016a562520e62a9df1f5558ba8f70/public/editor/scripts/editor/js/fc/bramble-ui-bridge.js#L95-L96

**Comment by simon66** [comment] 2017-01-26 20:19
I'd like to work on this feature (Since it's been opened for almost 2 years).
Looks like @flukeout is assigned to it already. Are you still working on it or should I implement it?
Thanks :+1:

**Comment by humphd** [comment] 2017-01-26 20:50
Go for it, @simon66

**Comment by simon66** [comment] 2017-01-28 19:27
I thought of 3 possibilities where we can have the export button:

1) When a "guest" (Not logged in user) starts a new project, this is how they can export the project
![capture1](https://cloud.githubusercontent.com/assets/1103528/22399100/ec27ed90-e563-11e6-85c5-0e6d4d8a326c.PNG)
2) We can add an export button here but I'm not too sure if this is a good spot (If they minimize the side bar, the export button is now hidden).
![capture2](https://cloud.githubusercontent.com/assets/1103528/22399111/14b37e3c-e564-11e6-9f71-85848a3b47aa.PNG)
3) We could also have the Export button here
![capture3](https://cloud.githubusercontent.com/assets/1103528/22399113/2218992c-e564-11e6-98de-9e1852799fae.PNG)

I prefer option 1 since it follows the same layout as a logged in user. This is good practice since a "guest" will eventually register and they should already know the layout.

Which option would be best? Is there another place you can think of?
Also, as for icons, is there a preferred place where I can get more icons? Depending on which option we go with, we will need more icons.

**Comment by Pomax** [comment] 2017-01-28 20:15
It feels like exporting should be associated with the project irrespective of the user, so I kind of like the idea of having it be an "always available" icon on the file tree, rather than keeping it in the user menu. @flukeout?

**Comment by humphd** [comment] 2017-01-28 21:09
I'd vote for the download button beside the '+' icon over the file tree.  @flukeout will need to approve whatever we do here.

**Comment by simon66** [comment] 2017-01-29 06:23
I also just thought about another option

![capture4](https://cloud.githubusercontent.com/assets/1103528/22402336/23c72cae-e5c1-11e6-973d-d1af39382f65.PNG)

Of course the icon will be changed to match the color scheme.

As for putting the icon on the file tree, what should be its behavior when the user minimizes the file tree? Should the Export button be hidden as well?
Waiting on @flukeout :)

**Comment by humphd** [comment] 2017-01-29 18:12
@simon66 it's too niche a feature to highlight so prominently with such a significant UI addition.

**Comment by flukeout** [comment] 2017-01-30 06:32
Hey @simon66 sorry for the hold up, made a note to jump on this first thing in the morning. Are you held up by design at this point?

**Comment by flukeout** [comment] 2017-01-30 07:01
Great work putting these options together, by the way. It does make sense putting the export feature closer to the files, it's an area that's visible for guests and signed-in users alike.

However, it clutters up that little bar with a feature that won't get used a lot. It might lead to mis-clicks which start a potentially big download immediately. Having just the small icon to communicate what it does might make the feature hard to find as well.

Another option would be to put a button below the list of files in the file tree. That gets more complicated though because we'd be messing with the brackets codebase. Is that something you'd be interested in exploring?

Anyway, I'll add some more thoughts tomorrow. I like the guest menu idea too.

Lastly I think ``Download files (.zip)`` might be a better label that a wider audience would understand.

**Comment by Pomax** [comment] 2017-01-30 09:33
another thought, what if "files" itself is a dropdown menu? `[files ▽]` with under that some options like "new file", "export", "import" etc, while keeping the dedicated [+] and collapse option?

**Comment by flukeout** [comment] 2017-01-30 17:38
Given all of the options, I'd like to go with the following...

![image](https://cloud.githubusercontent.com/assets/25212/22434052/6420b874-e6cf-11e6-96ad-20a4eacaa4fd.png)

The icon need some work, I'll create it.

Benefits
* This menu is already built and is tied closely with file-related actions

Drawbacks
* We lose the "+" icon, which is a super obvious for adding new files

However, with the right Icon, I think that's OK.

**Comment by flukeout** [comment] 2017-01-30 17:39
I also considered this approach, which is an adaptation of @Pomax's idea..

![image](https://cloud.githubusercontent.com/assets/25212/22434180/e40b4d24-e6cf-11e6-894b-83a35b71ab72.png)

I think this works pretty well also, but it's not as obvious and removes a common UI element that our users are already familiar with.

**Comment by Pomax** [comment] 2017-01-30 17:52
fair points - I'm kind of missing a "create a file" without html/css/js enforcement but for the Thimble audience that might not be a real problem.

**Comment by flukeout** [comment] 2017-01-30 17:54
Are you missing it for your own work flow? You can right-click the file tree and do it via the context menu.

**Comment by humphd** [comment] 2017-01-30 17:57
I love this change, and moving "Download files (.zip)" into that menu.  Great idea.

**Comment by Pomax** [comment] 2017-01-30 17:58
yeah I've been using the "hidden" right click menu in the file browser a lot, but I'm a bit more of a poweruser than most thimble users will be, I readily admit

**Comment by flukeout** [comment] 2017-01-30 18:01
@humphd just to clarify, you're referring to the first option I posted, yeah?

**Comment by simon66** [comment] 2017-01-30 18:17
@flukeout After looking at both options, I really like Option 2.
Let me know which option you prefer 👍

**Comment by flukeout** [comment] 2017-01-30 18:37
@simon66 I think you're right, and I think humph is referring to Option 2 as well. Let's roll with that, it feels better.

**Comment by humphd** [comment] 2017-01-30 19:38
I'm taking about this one:

 ![image](https://cloud.githubusercontent.com/assets/25212/22434052/6420b874-e6cf-11e6-96ad-20a4eacaa4fd.png)

**Comment by flukeout** [comment] 2017-01-30 19:45
@simon66 I'm going to collect some more feedback on this issue. In the meantime, continue with **Option 1** - it's the easier change, and if we decide to move to option 2, we can re-style the menu and add the affordance to the Files title in phase 2.

Does that sound OK?

**Comment by simon66** [comment] 2017-01-31 02:02
Perfect! I'm going with Option 1. I mean, it should be an easy change if we decide with Option 2.
I'll work on it and wait for the new icon :+1:

**Comment by simon66** [comment] 2017-02-01 04:21
![screen shot 2017-01-31 at 11 20 09 pm](https://cloud.githubusercontent.com/assets/1103528/22495164/e07c5152-e80b-11e6-90b0-fda1978bb40f.png)
Done! Waiting for the icon :)

**Comment by gideonthomas** [comment] 2017-02-01 04:30
@simon66 nice work! Would you be able to open up a PR with your changes so far? You could mark it as [WIP] in the title so that we know that it's an in progress PR.

**Comment by simon66** [comment] 2017-02-01 05:52
Hummm... well... thats super annoying... There where issues with my branch and while trying to fix them, looks like they show up here haha.
Either way, there shouldn't show on the commit history.

I've created a pull request @gideonthomas

**Comment by Pomax** [comment] 2017-02-01 07:50
@simon66 no worries, we can fix all of that with a rebase/squash once the code goes from work-in-progress to "read to be merged in" =)

**Comment by gideonthomas** [comment] 2017-02-09 04:03
Fixed with adf9a5f79f7828e2b025cc673c412dff823d2928

**Closed by gideonthomas** 2017-02-09 04:03 UTC
Labels: assigned to contributor, good first bug, UI
