### ISSUE TITLE
DEV: "npm run test" in brackets adds a bunch of files to repo.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2354] opened 2017-07-07 23:40 UTC
![image](https://user-images.githubusercontent.com/25212/27980383-ef5c3442-6332-11e7-9b15-2cecb623ba66.png)

Is that normal?

**Comment by gideonthomas** [comment] 2017-07-08 17:51
This is correct but should be git ignored.

Change needs to be made here: https://github.com/mozilla/brackets/blob/master/.gitignore to add the `.grunt` folder

**Comment by MhdTlb** [comment] 2017-07-16 02:52
Can I work on this issue?

**Comment by gideonthomas** [comment] 2017-07-16 15:19
sure thing @MhdTlb

**Comment by MhdTlb** [comment] 2017-07-21 02:24
@gideonthomas Please excuse my naive question. 
In the previous comment you sad that the fix should be under `bracket` project. So Why the issue is created here under `thimble`?
Also, How could I create a PR under `bracket` for an issue in `thimble`?

**Comment by ryanwarsaw** [comment] 2017-07-21 02:30
@MhdTlb Thimble embeds brackets and adds the features that makes the Thimble we know today, and brackets is the editor component of that (so when you edit your project files, that's brackets). 

As for why the issue is filed under Thimble, it's mostly just for organizational purposes. It helps to have all tickets in one location rather than spread out across many. 

As for your PR question, Github & Git are two different things. I'd recommend you take the quick Git tutorial (See: https://try.github.io/levels/1/challenges/1) it'll go through remotes, branches and all that fancy stuff that should help clear things up for you.

**Comment by gideonthomas** [comment] 2017-07-21 02:40
As @ryanwarsaw mentions, we use the thimble repository for tracking issues, even those that need to be fixed in Brackets. What you probably want to do is to clone the Brackets repository and work just with that for this specific issue.

Hopefully that helps.

**Comment by MhdTlb** [comment] 2017-07-21 02:47
Sorry @ryanwarsaw, it seems that my question is not clear. 
This issue is under [Thimble](https://github.com/mozilla/thimble.mozilla.org), I was excepting to change files that are under `thimble.mozilla.org` folder (my local repository). So When i push my changes they will go under my forked thimble project and I can link these changes to current issue.

But you said that changes should be made for [Bracket](https://github.com/mozilla/brackets). I assume I have to fork Bracket as well and make required changes. Under which issue would i push changes as there is no issue in Bracket related to current issue?

**Comment by ryanwarsaw** [comment] 2017-07-21 02:55
@MhdTlb We have an issue label `brackets` specifically for situations where an issue filed here references changes that need to be made in the brackets repository.

That is correct, you need to fork Brackets and have it running per the documentation (See; https://github.com/mozilla/thimble.mozilla.org#installing-brackets-bramble). Changes made in the brackets repository would be pushed to that repository, vise versa with Thimble. 

If you're trying to reference the issue, when you file the PR you can do so by writing: mozilla/thimble.mozilla.org#2354 for example, and you could reference that over in brackets and it'd link just as if you were to do #2354 here.

**Comment by gideonthomas** [comment] 2017-07-21 02:57
@ryanwarsaw would you be willing to contribute a PR to add this information to CONTRIBUTING.md as well?

**Comment by ryanwarsaw** [comment] 2017-07-21 02:59
@gideonthomas Did you have specific additions in mind? or just a general summary of the discussion above? I can send a PR sometime tomorrow, probably afternoon if that's okay.

**Comment by gideonthomas** [comment] 2017-07-21 03:01
Mainly about how to contribute to an issue with the Brackets label on it, i.e. create a PR against Brackets and reference the issue as you mention above. No urgency on the issue, feel free to do it whenever you have some spare time and feel like it :)

**Comment by MhdTlb** [comment] 2017-07-21 03:11
Thanks @ryanwarsaw. It's clear now!!! 👍

**Closed** 2017-07-21 16:11 UTC
Labels: Assigned to Contributor, brackets, Good First Bug
