### ISSUE TITLE
Files disappear from file tree after renaming index.html to something that throws an error.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1673] opened 2017-01-25 19:35 UTC
**Steps to reproduce**

* Create a new project
* Copy the markup in the index.html file to your clipboard
* Rename the index.html page
* Paste the markup into the filename and press enter
* It will throw an error
* Both files will disappear from the file view
* They return when you refresh the browser

![file](https://cloud.githubusercontent.com/assets/25212/22305933/3409413c-e2f2-11e6-8dd4-1e2ed1bdd155.gif)

**Comment by davidhuang1550** [comment] 2017-01-27 17:50
Id like to work on this.

**Comment by flukeout** [comment] 2017-01-27 18:27
Sounds good @davidhuang1550 - let me know if you're able to reproduce this issue.

**Comment by davidhuang1550** [comment] 2017-01-28 04:58
Got it, I was able to reproduce this issue.

**Comment by gideonthomas** [comment] 2017-02-01 01:52
@humphd any idea where the code might be that does error handling for renames?

**Comment by davidhuang1550** [comment] 2017-02-02 01:17
posted pull request to brackets because the issue was with the editor [here](https://github.com/mozilla/brackets/pull/571). 
Turns out the files did not disappear but instead the view was not properly shifted when the reversion was taken place.

**Comment by gideonthomas** [comment] 2017-02-06 01:56
Hi @davidhuang1550 just to confirm (since I'm a bit confused by [this comment](https://github.com/mozilla/brackets/pull/571#issuecomment-277564420)), you are still working on fixing this issue (since this is still happening)?

**Comment by davidhuang1550** [comment] 2017-02-06 02:26
@gideonthomas The issue seems to have been resolved. I cannot recreate the problem any longer locally and on the web.

**Comment by davidhuang1550** [comment] 2017-02-06 03:42
@gideonthomas can you still reproduce the problem?

**Comment by gideonthomas** [comment] 2017-02-06 18:03
Yeah I am able to reproduce this! I think I might know why you aren't able to reproduce this. You need to rename the `index.html` file. It doesn't seem to be an issue with any other HTML file. @davidhuang1550 can you try doing that?

**Comment by davidhuang1550** [comment] 2017-02-06 18:47
@gideonthomas I tried it on the main thimble web page.

![ezgif com-841cb8fdb8](https://cloud.githubusercontent.com/assets/22035024/22661225/9fd72076-ec72-11e6-9260-424db1a2d80d.gif)

**Comment by flukeout** [comment] 2017-02-06 18:51
@davidhuang1550 before you rename the index.html file. Click on it so that it is highlighted.

![image](https://cloud.githubusercontent.com/assets/25212/22661431/398dbb62-ec5a-11e6-9267-50156549e13c.png)

That's what does it for me.

**Comment by davidhuang1550** [comment] 2017-02-06 18:57
@flukeout Huh, that's weird it wasn't like this before. I will try and get this done today!

**Comment by davidhuang1550** [comment] 2017-02-07 19:13
@flukeout @gideonthomas I tried changing the _renderTreeSync function in projectManager.js in Brackets by changing the first parameter of setScrollerInfo. Every seemed to work properly after that.  Do you guys think this is the correct fix?

Before
<img width="907" alt="screen shot 2017-02-07 at 2 09 18 pm" src="https://cloud.githubusercontent.com/assets/22035024/22706966/28749ffe-ed3f-11e6-8683-5cbf1506cb38.png">


After
<img width="890" alt="screen shot 2017-02-07 at 2 08 56 pm" src="https://cloud.githubusercontent.com/assets/22035024/22706959/21d56840-ed3f-11e6-9b61-110d601c88c0.png">

**Comment by humphd** [comment] 2017-02-07 20:46
@davidhuang1550 I notice that the first arg is the width of the tree container, see:

https://github.com/adobe/brackets/blob/0d1630c47fefa98269f1bb0937e22d5934749cd3/src/project/ProjectModel.js#L327-L337

I don't think using `0` makes sense, since the tree container's width isn't actually zero.  What happens if you force a call to `_renderTreeSync(true)` in the error path that you're hitting (i.e., `true` to force the render)?

**Comment by davidhuang1550** [comment] 2017-02-07 21:50
@humphd Opps, i meant to change the third parameter instead of the first. My intention was to move the scroll left to 0 to the beginning of the view so that we can see the filetree, and not set the size of the actual width of the filetree to 0.

**Comment by humphd** [comment] 2017-02-07 22:07
Interesting.  Yeah, do a PR that does this, let's test.

**Comment by gideonthomas** [comment] 2017-02-08 22:45
Fixed with https://github.com/mozilla/brackets/commit/5dbb556826cc4e5bb1f23d725562df84f2018b53

**Closed by gideonthomas** 2017-02-08 22:45 UTC
Labels: assigned to contributor, bug, good first bug
