### ISSUE TITLE
Editor stuck, unable to publish project for user...

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2018] opened 2017-04-21 18:35 UTC
Here's a screenshot of the editor stuck in the "Publishing" step, including the error message in the green bar...

![image](https://cloud.githubusercontent.com/assets/25212/25291265/31219118-2686-11e7-9ac9-b748f6905144.png)

This is the ``fileSavingFailedIndicator`` error, or "Saving failed, retrying..." in English.

cc @humphd @gideonthomas - this seems familiar, do we have a canned solution? 

I will ask about the amount of images & size of the images in the folder, which has caused this kind of trouble before.

**Comment by humphd** [comment] 2017-04-21 18:45
It's usually due to something in the backend.  cc @cadecairos

**Comment by flukeout** [comment] 2017-04-21 18:47
Projects are publishing fine otherwise, I tested after getting the email - will update ticket once I find out about the amount of images.

**Comment by flukeout** [comment] 2017-04-21 19:48
@humphd looks like it's an image that is over 1MB (1.1MB to be exact) that's causing this. The use can no longer delete the file form the project either - this is something we've seen before and we should address it. Can we cap the upload size at 1MB or something like that?

**Comment by humphd** [comment] 2017-04-21 19:50
Are you able to get more details for me?  If they reload the page with `?logging=1` on the URL, it will cause more sync info to get recorded in the console.  Then they could give us the contents of the console logs?

I can't believe this is being caused by a 1M file on its own.  Also, which browser, OS, etc.

**Comment by flukeout** [comment] 2017-04-21 20:28
I'll ask them to do that, the 1mb thing doesn't seem too unreasonable to me, we've had weird image issues in the past.

**Comment by flukeout** [comment] 2017-04-21 20:39
In testing on my own, I'm able to include a few images that are between 1.5 and 2 mb and publish successfully.

**Comment by flukeout** [comment] 2017-04-21 20:51
@humphd here's the console output - https://pastebin.com/WfL9cnWE

**Comment by humphd** [comment] 2017-04-21 20:57
OK, so here's what we care about:

```
main.js:3 [Thimble LOG (module=SyncManager)] start syncing
main.js:12 [HTMLRewriter warning] couldn't get URL for `/635034/projects/920330/images/Logo.lespetitsdebrouillards.png`
main.js:12 [HTMLRewriter warning] couldn't get URL for `/635034/projects/920330/images/toiturevege3.jpg`
main.js:11 [CSSRewriter warning] failed on `../fonts/roboto/Roboto-Thin.woff2` not found
main.js:11 [CSSRewriter warning] failed on `../fonts/roboto/Roboto-Light.woff2` not found
main.js:11 [CSSRewriter warning] failed on `../fonts/roboto/Roboto-Regular.woff2` not found
main.js:11 [CSSRewriter warning] failed on `../fonts/roboto/Roboto-Medium.woff2` not found
main.js:11 [CSSRewriter warning] failed on `../fonts/roboto/Roboto-Bold.woff2` not found
main.js:3 [Thimble LOG (module=SyncManager)] starting sync /635034/projects/920330/toiturevege1.jpg update
8f70f6ed-8bd7-4bcb-8879-4660f863e5c8:1590 Mixed Content: The page at 'https://thimble.mozilla.org/fr/user/cortek29/920330?logging=1' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/icon?family=Material+Icons'. This request has been blocked; the content must be served over HTTPS.
main.js:3 [Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e
main.js:3 [Thimble LOG (module=project)] queueFileUpdate /635034/projects/920330/toiturevege1.jpg
main.js:3 [Thimble LOG (module=SyncManager)] progress event - pending paths to sync: 2
main.js:3 [Thimble LOG (module=SyncManager)] finished current operation (failed), will run next in 276ms. 2 operation(s) remain.
Logo.lespetitsdebrouillards.png Failed to load resource: the server responded with a status of 404 (Not Found)
toiturevege3.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
main.js:3 [Thimble LOG (module=SyncManager)] starting sync /635034/projects/920330/toiturevege2.jpg update
main.js:3 [Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e
main.js:3 [Thimble LOG (module=project)] queueFileUpdate /635034/projects/920330/toiturevege2.jpg
main.js:3 [Thimble LOG (module=SyncManager)] progress event - pending paths to sync: 2
main.js:3 [Thimble LOG (module=SyncManager)] finished current operation (failed), will run next in 332ms. 2 operation(s) remain.
main.js:3 [Thimble LOG (module=SyncManager)] starting sync /635034/projects/920330/toiturevege1.jpg update
main.js:3 [Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e
main.js:3 [Thimble LOG (module=project)] queueFileUpdate /635034/projects/920330/toiturevege1.jpg
main.js:3 [Thimble LOG (module=SyncManager)] progress event - pending paths to sync: 2
main.js:3 [Thimble LOG (module=SyncManager)] finished current operation (failed), will run next in 176ms. 2 operation(s) remain.
main.js:3 [Thimble LOG (module=SyncManager)] starting sync /635034/projects/920330/toiturevege2.jpg update
main.js:3 [Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e
main.js:3 [Thimble LOG (module=project)] queueFileUpdate /635034/projects/920330/toiturevege2.jpg
main.js:3 [Thimble LOG (module=SyncManager)] progress event - pending paths to sync: 2
main.js:3 [Thimble LOG (module=SyncManager)] finished current operation (failed), will run next in 1728ms. 2 operation(s) remain.
main.js:3 [Thimble LOG (module=SyncManager)] starting sync /635034/projects/920330/toiturevege1.jpg update
main.js:3 [Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e
main.js:3 [Thimble LOG (module=project)] queueFileUpdate /635034/projects/920330/toiturevege1.jpg
main.js:3 [Thimble LOG (module=SyncManager)] progress event - pending paths to sync: 2
main.js:3 [Thimble LOG (module=SyncManager)] finished current operation (failed), will run next in 5881ms. 2 operation(s) remain.
main.js:3 [Thimble LOG (module=SyncManager)] starting sync /635034/projects/920330/toiturevege2.jpg update
main.js:3 [Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e
main.js:3 [Thimble LOG (module=project)] queueFileUpdate /635034/projects/920330/toiturevege2.jpg
main.js:3 [Thimble LOG (module=SyncManager)] progress event - pending paths to sync: 2
/fr/editor/scripts/main.js:3 [Thimble LOG (module=SyncManager)] finished current operation (failed), will run next in 9103ms. 2 operation(s) remain.
8f70f6ed-8bd7-4bcb-8879-4660f863e5c8:154 Runtime.evaluate
/fr/editor/scripts/main.js:3 [Thimble LOG (module=SyncManager)] starting sync /635034/projects/920330/toiturevege1.jpg update
/fr/editor/scripts/main.js:3 [Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e
/fr/editor/scripts/main.js:3 [Thimble LOG (module=project)] queueFileUpdate /635034/projects/920330/toiturevege1.jpg
/fr/editor/scripts/main.js:3 [Thimble LOG (module=SyncManager)] progress event - pending paths to sync: 2
/fr/editor/scripts/main.js:3 [Thimble LOG (module=SyncManager)] finished current operation (failed), will run next in 7536ms. 2 operation(s) remain.
8f70f6ed-8bd7-4bcb-8879-4660f863e5c8:154 Runtime.evaluate
/fr/editor/scripts/main.js:3 [Thimble LOG (module=SyncManager)] starting sync /635034/projects/920330/toiturevege2.jpg update
/fr/editor/scripts/main.js:3 [Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e
/fr/editor/scripts/main.js:3 [Thimble LOG (module=project)] queueFileUpdate /635034/projects/920330/toiturevege2.jpg
/fr/editor/scripts/main.js:3 [Thimble LOG (module=SyncManager)] progress event - pending paths to sync: 2
/fr/editor/scripts/main.js:3 [Thimble LOG (module=SyncManager)] finished current operation (failed), will run next in 18986ms. 2 operation(s) remain.
/fr/editor/scripts/main.js:3 [Thimble LOG (module=SyncManager)] starting sync /635034/projects/920330/toiturevege1.jpg update
/fr/editor/scripts/main.js:3 [Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e
/fr/editor/scripts/main.js:3 [Thimble LOG (module=project)] queueFileUpdate /635034/projects/920330/toiturevege1.jpg
/fr/editor/scripts/main.js:3 [Thimble LOG (module=SyncManager)] progress event - pending paths to sync: 2
/fr/editor/scripts/main.js:3 [Thimble LOG (module=SyncManager)] finished current operation (failed), will run next in 19324ms. 2 operation(s) remain.
8f70f6ed-8bd7-4bcb-8879-4660f863e5c8:154 Runtime.evaluate
blob:https://mozillathimblelivepreview.net/8f70f6ed-8bd7-4bcb-8879-4660f863e5c8:1 Mixed Content: The page at 'https://thimble.mozilla.org/fr/user/cortek29/920330?logging=1' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/icon?family=Material+Icons'. This request has been blocked; the content must be served over HTTPS.
main.js:3 [Thimble LOG (module=SyncManager)] starting sync /635034/projects/920330/toiturevege2.jpg update
main.js:3 [Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e {name: "ENOENT", code: "ENOENT", errno: 34, message: "O_CREATE is not set and the named file does not exist", path: "/635034/projects/920330/toiturevege2.jpg"…}
main.js:3 [Thimble LOG (module=project)] queueFileUpdate /635034/projects/920330/toiturevege2.jpg
main.js:3 [Thimble LOG (module=SyncManager)] progress event - pending paths to sync: 2
main.js:3 [Thimble LOG (module=SyncManager)] finished current operation (failed), will run next in 18625ms. 2 operation(s) remain.
main.js:3 [Thimble LOG (module=SyncManager)] starting sync /635034/projects/920330/toiturevege1.jpg update
main.js:3 [Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e {name: "ENOENT", code: "ENOENT", errno: 34, message: "O_CREATE is not set and the named file does not exist", path: "/635034/projects/920330/toiturevege1.jpg"…}
main.js:3 [Thimble LOG (module=project)] queueFileUpdate /635034/projects/920330/toiturevege1.jpg
main.js:3 [Thimble LOG (module=SyncManager)] progress event - pending paths to sync: 2
main.js:3 [Thimble LOG (module=SyncManager)] finished current operation (failed), will run next in 15891ms. 2 operation(s) remain.
bramble-sw.js:1 Service Worker termination by a timeout timer was canceled because DevTools is attached.
main.js:3 [Thimble LOG (module=SyncManager)] starting sync /635034/projects/920330/toiturevege2.jpg update
main.js:3 [Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e {name: "ENOENT", code: "ENOENT", errno: 34, message: "O_CREATE is not set and the named file does not exist", path: "/635034/projects/920330/toiturevege2.jpg"…}
main.js:3 [Thimble LOG (module=project)] queueFileUpdate /635034/projects/920330/toiturevege2.jpg
main.js:3 [Thimble LOG (module=SyncManager)] progress event - pending paths to sync: 2
main.js:3 [Thimble LOG (module=SyncManager)] finished current operation (failed), will run next in 7978ms. 2 operation(s) remain.
main.js:3 [Thimble LOG (module=SyncManager)] starting sync /635034/projects/920330/toiturevege1.jpg update
main.js:3 [Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e {name: "ENOENT", code: "ENOENT", errno: 34, message: "O_CREATE is not set and the named file does not exist", path: "/635034/projects/920330/toiturevege1.jpg"…}
main.js:3 [Thimble LOG (module=project)] queueFileUpdate /635034/projects/920330/toiturevege1.jpg
main.js:3 [Thimble LOG (module=SyncManager)] progress event - pending paths to sync: 2
main.js:3 [Thimble LOG (module=SyncManager)] finished current operation (failed), will run next in 9073ms. 2 operation(s) remain.
main.js:3 [Thimble LOG (module=SyncManager)] starting sync /635034/projects/920330/toiturevege2.jpg update
main.js:3 [Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e {name: "ENOENT", code: "ENOENT", errno: 34, message: "O_CREATE is not set and the named file does not exist", path: "/635034/projects/920330/toiturevege2.jpg"…}
main.js:3 [Thimble LOG (module=project)] queueFileUpdate /635034/projects/920330/toiturevege2.jpg
main.js:3 [Thimble LOG (module=SyncManager)] progress event - pending paths to sync: 2
main.js:3 [Thimble LOG (module=SyncManager)] finished current operation (failed), will run next in 477ms. 2 operation(s) remain.
main.js:3 [Thimble LOG (module=SyncManager)] starting sync /635034/projects/920330/toiturevege1.jpg update
main.js:3 [Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e {name: "ENOENT", code: "ENOENT", errno: 34, message: "O_CREATE is not set and the named file does not exist", path: "/635034/projects/920330/toiturevege1.jpg"…}
main.js:3 [Thimble LOG (module=project)] queueFileUpdate /635034/projects/920330/toiturevege1.jpg
main.js:3 [Thimble LOG (module=SyncManager)] progress event - pending paths to sync: 2
main.js:3 [Thimble LOG (module=SyncManager)] finished current operation (failed), will run next in 17450ms. 2 operation(s) remain.
main.js:3 [Thimble LOG (module=SyncManager)] starting sync /635034/projects/920330/toiturevege2.jpg update
main.js:3 [Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e {name: "ENOENT", code: "ENOENT", errno: 34, message: "O_CREATE is not set and the named file does not exist", path: "/635034/projects/920330/toiturevege2.jpg"…}
main.js:3 [Thimble LOG (module=project)] queueFileUpdate /635034/projects/920330/toiturevege2.jpg
main.js:3 [Thimble LOG (module=SyncManager)] progress event - pending paths to sync: 2
main.js:3 [Thimble LOG (module=SyncManager)] finished current operation (failed), will run next in 2505ms. 2 operation(s) remain.
main.js:3 [Thimble LOG (module=SyncManager)] starting sync /635034/projects/920330/toiturevege1.jpg update
main.js:3 [Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e {name: "ENOENT", code: "ENOENT", errno: 34, message: "O_CREATE is not set and the named file does not exist", path: "/635034/projects/920330/toiturevege1.jpg"…}
main.js:3 [Thimble LOG (module=project)] queueFileUpdate /635034/projects/920330/toiturevege1.jpg
main.js:3 [Thimble LOG (module=SyncManager)] progress event - pending paths to sync: 2
main.js:3 [Thimble LOG (module=SyncManager)] finished current operation (failed), will run next in 5752ms. 2 operation(s) remain.
main.js:3 [Thimble LOG (module=SyncManager)] starting sync /635034/projects/920330/toiturevege2.jpg update
main.js:3 [Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e {name: "ENOENT", code: "ENOENT", errno: 34, message: "O_CREATE is not set and the named file does not exist", path: "/635034/projects/920330/toiturevege2.jpg"…}
main.js:3 [Thimble LOG (module=project)] queueFileUpdate /635034/projects/920330/toiturevege2.jpg
main.js:3 [Thimble LOG (module=SyncManager)] progress event - pending paths to sync: 2
main.js:3 [Thimble LOG (module=SyncManager)] finished current operation (failed), will run next in 3774ms. 2 operation(s) remain.
main.js:3 [Thimble LOG (module=SyncManager)] starting sync /635034/projects/920330/toiturevege1.jpg update
main.js:3 [Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e {name: "ENOENT", code: "ENOENT", errno: 34, message: "O_CREATE is not set and the named file does not exist", path: "/635034/projects/920330/toiturevege1.jpg"…}
main.js:3 [Thimble LOG (module=project)] queueFileUpdate /635034/projects/920330/toiturevege1.jpg
main.js:3 [Thimble LOG (module=SyncManager)] progress event - pending paths to sync: 2
main.js:3 [Thimble LOG (module=SyncManager)] finished current operation (failed), will run next in 19209ms. 2 operation(s) remain.
```

It looks to me like it wants to sync 2 files, but they no longer exist in the filesystem:

```
main.js:3 [Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e {name: "ENOENT", code: "ENOENT", errno: 34, message: "O_CREATE is not set and the named file does not exist", path: "/635034/projects/920330/toiturevege2.jpg"…}
...
main.js:3 [Thimble LOG (module=SyncManager)] error syncing file, requeuing operation e {name: "ENOENT", code: "ENOENT", errno: 34, message: "O_CREATE is not set and the named file does not exist", path: "/635034/projects/920330/toiturevege1.jpg"…}
```

So it finishes the sync, fails it, and decides to try again.  That's a bug on our part: we shouldn't keep trying to sync a file that is returning `ENOENT` when we read it; we should remove that from the sync queue.

For now, have the user try creating the files manually, and the sync should finish.  Then they can delete them.

**Comment by flukeout** [comment] 2017-04-21 22:11
Just as a follow-up to this, it seems like the user was able to get back to a workable state, although I think it was because they fired it up in Firefox. Then later they cleared their Chrome cache, which also seemed to resolve things in Chrome.

In the end, I'm not sure if they followed the instructions that I suggested (to manually add the missing files to the root) - but at least, they are back to good. As for this issue, I'm going to close it and @humphd will re-file an issue that aims to address the root cause of this happening.

**Comment by flukeout** [comment] 2017-04-21 22:11
Re-opening until @humphd files a follow-up so we don't lose track.

**Comment by humphd** [comment] 2017-04-21 22:13
I'm fixing now, will have a PR up tonight.

**Comment by flukeout** [comment] 2017-04-21 22:13
Ok, let's keep this issue up until the PR closes it.

**Comment by Cortek29** [comment] 2017-04-21 22:42
It was not only using firefox that solved the problem, because even after successfully deleting the problem file under firefox, under chrome, the problem persisted. In the screenshots that I later provided chrome and firefox in parallel, the same Thimble session opened at the same time in both browsers, one can clearly see that in the folder 'images' the file' toiturevege1 .png 'appears then under firefox it is absent ...
It's only when I erased the chrome cover that everything returned to normal.
Thanks a lot for your help :)

**Comment by humphd** [comment] 2017-04-21 22:44
@Cortek29 thanks for jumping in here with details, it's really appreciated.  Would you be able to put those screenshots in the bug?  And any info you have about what you did?

I'm currently writing a fix for this, and want to test it locally.  If I can trigger it in a local build, that would be ideal.  Thanks for any help, and sorry you had to waste time on Thimble not working.

**Comment by Cortek29** [comment] 2017-04-21 22:49
![2017_04_21_23_27_44_mozilla_thimble-chrome](https://cloud.githubusercontent.com/assets/7837675/25298480/8588128a-26f5-11e7-8cf9-10db0afa1c80.png)
![2017_04_21_23_28_27_photos-firefox](https://cloud.githubusercontent.com/assets/7837675/25298481/858ca5b6-26f5-11e7-95df-3a33d01fc55d.png)

**Comment by humphd** [comment] 2017-04-21 22:53
Thanks, also filed https://github.com/mozilla/thimble.mozilla.org/issues/2025 for another bug I see there.

**Closed** 2017-04-26 20:20 UTC
Labels: support
