### ISSUE TITLE
Error 404 on Preview Page l Non-responsive on a single device l No known issues with used device.

### ISSUE THREAD

**Issue by Ghostwolf199927** [mozilla/thimble.mozilla.org#2553] opened 2017-11-10 21:57 UTC
Browser: Chrome
Chrome Version: 63.0.3239.42 beta
Device: C720 Acer Chromebook
![screenshot 2017-11-10 at 3 48 09 pm](https://user-images.githubusercontent.com/33559018/32680246-636809ce-c62f-11e7-8c53-8b9521d59178.png)

This error is happening 24/7, the error seems to be bound to my device (Chromebook Acer) and it's becoming a bit of a problem when I'm trying to work on a project or side project.

I'm unable to check the browser dev tools because my Chromebook is managed by my company.

**Comment by Ghostwolf199927** [comment] 2017-11-10 22:02
Not being able to see a preview of the page is frusterating and it slows me down on work pace...So you can please fix this? I wish I could see the preview with this device..Also, other Company managed devices are having no problems with this like I am..I'm certain It's not an extension/hardware issue.

**Comment by josephbabu** [comment] 2017-11-17 04:15
Try Firefox working fine
https://thimbleprojects.org/josephbabu/357969

**Comment by ryanwarsaw** [comment] 2017-11-17 05:44
@gideonthomas Is this by any chance related to #2468? Error seems to be identical, but instructions for reproducing are different. Worth noting I had this issue happen to about a half dozen machines during my session as well, I wasn't able to figure out what was causing it.

**Comment by humphd** [comment] 2017-11-20 14:17
This was fixed by https://github.com/mozilla/brackets/pull/894.  See http://blog.humphd.org/promise-to-catch/ for more details.

**Closed by humphd** 2017-11-20 14:17 UTC
