### ISSUE TITLE
With last update export project disappeared

### ISSUE THREAD

**Issue by lossendiere** [mozilla/thimble.mozilla.org#2171] opened 2017-05-18 09:41 UTC
I'm teacher and my school have bad connexion, sometimes need export project to continue offline
But with last update of mozilla timble i can't see this function

It's possible to have again this function ?

**Comment by humphd** [comment] 2017-05-18 15:06
@lossendiere sorry to confuse you with the latest change--the feature is still there, [just been moved](https://github.com/mozilla/thimble.mozilla.org/issues/2157):

![screen shot 2017-05-17 at 10 14 56 am](https://cloud.githubusercontent.com/assets/427398/26158403/c2f03f78-3ae9-11e7-9330-38fa84fe7896.png)

We did this to try and solve another problem, namely, people wanting to be able to export projects without needing to be logged in or having an account.  In the old way of doing it, we only showed that Export option in your user menu, which restricted its access.

Given that you're the second person in as many days to file this bug, I wonder if we should figure out a better solution; maybe duplicating the feature in both places.  I'll work with our team to try and fix this so it doesn't confuse other people.

Thanks for jumping into Github to file this, and letting us know your needs.  It's great to hear from our users.  I'm also interested in your discussion about poor connections and working offline.  The next major feature we're planning is 100% offline access in browsers that support it, so people can work even if they have no internet.

I'm going to close this as a duplicate of #2157, and try to solve things there.

**Closed by humphd** 2017-05-18 15:06 UTC

**Comment by humphd** [comment] 2017-05-18 16:15
Fix incoming in https://github.com/mozilla/thimble.mozilla.org/pull/2174

**Comment by lossendiere** [comment] 2017-05-19 08:00
Thanks to answer very quickly David.

The school year almost finish in end of june can test the Thimble mozilla
offline in septembre with students, but if you need someone to test during
july or agust i'm volunteer.

I'm french teacher in junior hight school, so if you need help for doing
some translation or create lesson in french about Mozilla thimble it's OK

Best regard

2017-05-18 17:06 GMT+02:00 David Humphrey <notifications@github.com>:
